### ISSUE TITLE
Query algebra based on QScript

### ISSUE THREAD

**Issue by wemrysi** [precog/quasar#1262]
Add a new algebra for queries that uses QScript instead of `LogicalPlan`. It'd be nice if this didn't live in `fs` as there appears to be a natural separation between the "filesystem" data wrangling operations and the ability to evaluate queries.

**Comment by alissapajer** [comment]
@wemrysi could you clarify this ticket a bit? Are you thinking about how `ExecutePlan`, `EvaluatePlan`, and `Explain` use `LogicalPlan`? And then this ticket would be to create an algebra for `QScript`? 

Though, I'm not convinced that the file system algebras need to know about `LogicalPlan` at all anymore, and perhaps we can just use `QScript` instead.

**Comment by sellout** [comment]
@alissapajer Yeah, we should basically `s/LogicalPlan/QScriptInternal/` in `QueryFile`, not create a new algebra. But then it sounds like this issue may cover other things beyond that.

**Comment by wemrysi** [comment]
Yes to the `s/LP/QScriptInternal` replacement, but I was also thinking that, if we created the `MetaFile` algebra (#1263), then the query parts of the current `QueryFile` algebra could become their own algebra, call it `Query` for the sake of argument, separate from the rest of the filesystem.

It seems like the non-query filesystem operations are complete on their own, and could even be a standalone module. Then our quasar api would become `Quasar[A] = Coproduct[Query, FileSystem, A]`.

I'm not sure if this will make anything more or less useful, I was just thinking about it from a separation of concerns standpoint and hadn't gotten much further than that.
