### ISSUE TITLE
Type.glb wrong with `Const(NA)`

### ISSUE THREAD

**Issue by sellout** [precog/quasar#1335]
Just saw this error in a CI build for an unrelated change.

```
[error]   x glb symmetric
[error]    Falsified after 71 passed tests.
[error]    > ARG_0: Const(Obj(Map($date -> Str(Jan 1))))
[error]    > ARG_1: Coproduct(Const(NA),Const(Obj(Map($date -> Str(Jan 1)))))
[error]    > 'Const(Obj(Map($date -> Str(Jan 1))))'
[error]    
[error]     is not equal to 
[error]    
[error]    'Coproduct(Const(NA),Const(Obj(Map($date -> Str(Jan 1)))))' (types.scala:30)
[error] Actual:   Co[]nst([]Ob...))[]
[error] Expected: Co[product(Co]nst([NA),Const(]Ob...))[)]
```

**Comment by mossprescott** [comment]
See [SD-1527: Type system is inconsistent: Data.NA.datatype = Type.Bottom](https://slamdata.atlassian.net/browse/SD-1527)

**Comment by jdegoes** [comment]
@sellout Probably whoever finds these errors needs to fix them right then and there. It's the only way they're going to be fixed.

**Comment by zeeiyerWork** [comment]
@nicflores -> Can you check with @sellout if this is still a thing?

**Comment by sellout** [comment]
Hopefully by June this will be replaced by EJson and TypeF. We shouldn't have the same issue there.
