### ISSUE TITLE
optimization: inline small data sets

### ISSUE THREAD

**Issue by jdegoes** [precog/quasar#1384]
Small data sets, particularly used in a subselect or JOIN, can be inlined and the resulting query further simplified. This would lead to quite significant performance improvements in cases where (small) reference data is stored in the database and joined dynamically with the operational data.

Further, this optimization could be applied to virtually any backend, with nothing more than the capacity to read the data set from the backend.

**Comment by mossprescott** [comment]
Sounds pretty slick.

We now have code to retrieve very simple statistics from MongoDB about collections for the planner (row count and approximate total size in bytes, currently). We would probably want to expose something like that in the algebras so we can use this information at the QScript level.
