### ISSUE TITLE
Eliminate dependency on scala-parser-combinators

### ISSUE THREAD

**Issue by paulp** [precog/quasar#1417]
Scala library combinators are sloooow, and not just in theory - I only became aware of [this parser](https://github.com/quasar-analytics/quasar/blob/master/core/src/main/scala/quasar/sql/parser.scala) because the profiler fingers it as a performance criminal.

Not expecting anyone to act on this, just opening so I don't forget. I took a flier a while back at replacing it with fastparse, which I thought I had heard was drop-in, but it was very not-drop-in.

**Comment by sellout** [comment]
Awww, I was hoping this was a PR.

Maybe this will light an invertible-syntax fire under @mossprescott 😉

**Comment by mossprescott** [comment]
@paulp: I assume this is a hot spot only in our tests which do a lot of query parsing/planning and no actual execution. But no doubt it's still worth improving.

@sellout: I'm not all that confident that invertible-syntax with coproducts will be performance competitive, but anything's possible.
