### ISSUE TITLE
make path representation more flexible

### ISSUE THREAD

**Issue by sellout** [precog/quasar#1433]
Right now, `Read` conversion will expand any directories until we reach files. In some stores (at least MarkLogic), queries can be performed on directories directly and this expansion is problematic.

It would be useful to separate `Read` conversion from directory expansion. Here are the things to think about:
1. the easiest (from QScript perspective) would be to loosen `Read` to take `AbsPath` instead of `AbsFile`, but then backends that choose directory expansion lose the type guarantee that they’re dealing exclusively with files;
2. this could be fixed by parameterizing `Read` (and `ShiftedRead`) over the path representation, but then `QScriptTotal` would need to contain both versions of `Read` (and both versions of `ShiftedRead`); but
3. that could then be fixed with mutually-recursive data structures, which fixes a bunch of things we’ve been working around in QScript.

**Comment by beckyconning** [comment]
This sounds like a really good approach. 

Would this allow for the reading of "things which can be queried generally" to be separate from the expanding "things which can only be queried only to reach things which can be queried generally" until we reach things which can be queried generally, regardless of whether the source considers them files/directories or documents/databases or values/objects or posts/users?

**Comment by sellout** [comment]
@beckyconning So, that’s a good question … it’s possible that a connector would have multiple stages of things – directory-like things that are not queryable, and both directory- and file-like things that are queryable. In which case, restricting the type after directory expansion would be undesirable (does anyone know of a system like that?)

Originally, I wanted connectors to have full control over the path representation, so they wouldn’t have to use pathy at all, and could have something that maps better to the store’s layout. But with the current approach, that would involve exposing more of the `Read` conversion internals (and is basically impossible until we get mutual recursion anyway), but something to think about.

**Comment by alissapajer** [comment]
@sellout would it make sense to have `ReadFile` and `ReadDirectory` as replacements for what's currently `Read`? And then when a backend elects to perform read conversion, it chooses either the file or directory flavor. 

`ReadFile` would guarantee that its expansion ends in a file, while the `ReadDirectory` expansion could end in either a file or a directory.

**Comment by sellout** [comment]
@alissapajer Yeah, I was thinking of representing that with something like `Read[AbsFile]` and `Read[AbsPath]` respectively. Then we’d also need `ShiftedRead[A]`. The problem is just that all four of those would need to be in `QScriptTotal`.

**Comment by jdegoes** [comment]
I've thought of a path as basically a reified optic, maybe a little less powerful, but essentially a list of nodes where each node indicates a way to zoom in or split, describing a selection of data that could be reached by focusing. Currently we have projection `/foo/bar/` but I'd like paths to be generalized across the API and everywhere else to something more like `/foo/*/bar/*/`, etc. (maybe further).

**Comment by sellout** [comment]
@jdegoes Right. “Pure” QScript has four components that work like that: `Root`, `ProjectField`, `LeftShift` (`*`), and also `Union`. So you can build something like `/foo/{bar|baz}/*`.

But data stores don’t usually have this level of flexibility. So we have optional transformations that are intended to help align the representation with the store.

So, we can convert a path like that above into something like `/foo/bar/a ∪ /foo/bar/b ∪ /foo/baz/c ∪ /foo/baz/d`. Then there’s a second optional transformation for stores that natively store collections, where each path has an implied `LeftShift` at the end (vs stores like MarkLogic, where each file actually represents a single datum).

Currently the path conversion assumes that the stores only allow querying at the “file” level. So, if some path ends up as a directory, we get the full tree of files from that dir and union them together (inserting `MakeMap` around files at varying depths to keep the structure intact). But it turns out that at least MarkLogic can query directories. So that connector currently needs to either avoid path conversion completely and perform it manually in the planner, or needs to fake out path conversion and tell us that directories are actually files (which is what it currently does).

So this ticket is about separating that file expansion from path conversion. For Mongo, we’d apply both, and then the planner only needs to deal with files (collections). Whereas MarkLogic would apply path conversion, but not expansion, so its QScript plan may contain both directories and files.

**Comment by paulp** [comment]
I've been down this road before, and I found it necessary to draw a distinction between a MetaPath and a Path. The former is effectively a computation which may describe multiple paths like "a/*/b", the latter is literal. (You can model a relative path as a virtual/meta one as well...)

If/when there are multiple layers of path translation like this, it should serve to highlight the problem I was talking about with escaping.

**Comment by sellout** [comment]
@paulp Yeah, that is effectively the distinction that’s being made. Path conversion runs the computation (which is a subset of QScript), getting filesystem info from the mount, and returning some set of literal paths.
