### ISSUE TITLE
Improve handling of outer joins

### ISSUE THREAD

**Issue by jdegoes** [precog/quasar#1472]
See [here](https://groups.google.com/forum/#!msg/slamdata-user/p6Wm6TN4Y2U/mG6iqI53AgAJ) for context.

I am not sure what is happening, but possibly, the type inferencer needs to be aware of outer joins such that it will not filter away undefineds from the appropriate side.

Probably, we should also take this opportunity to give the proper semantics to nulls (sentinel value) versus undefineds (error on operation).

**Comment by zeeiyerWork** [comment]
May be fixed - please take a look in May to confirm that it is not reproducible.

**Comment by alissapajer** [comment]
Tangentially related to #2385. Ping @nicflores and @jsantos17.
