### ISSUE TITLE
Handle the `ThetaJoin` `JoinType` in the MarkLogic planner

### ISSUE THREAD

**Issue by wemrysi** [precog/quasar#1505]
It is currently ignored which, I _think_, means all joins are implicitly inner.

**Comment by wemrysi** [comment]
This will likely require more plan analysis and breaking joins up into multiple steps rather than the single (naive) `FLWOR` expression currently used.

**Comment by sellout** [comment]
@wemrysi As always, think about ways that QScript could potentially make this easier.

In Mongo, all joins are outer joins (full outer in `mapReduce` or left outer in `$lookup`), and we post-filter cases with undefined values on one side or the other.
