### ISSUE TITLE
Implement common subexpression elimination

### ISSUE THREAD

**Issue by sellout** [precog/quasar#1549]
This is an optimization that would pull out more common substructures to eliminate duplicated work.

This would be handled differently depending on exactly where the common expressions are found, and the abilities of the connector. E.g., if a connector supports `Let`, then we could use them within a FreeMap. Otherwise, we could de-normalize a `qscript.Map` into two Maps, one setting up values to be used by the second. And there may be other representations for other dimensional situations.

**Comment by alissapajer** [comment]
@djspiewak see this old ticket for tracking `Let` bindings in `FreeMap`, or whatever solution we decide on.
