### ISSUE TITLE
Eliminate hard-coded “left” and “right” for join access.

### ISSUE THREAD

**Issue by sellout** [precog/quasar#1556]
In LP, it’s implied that a join creates a Map with the fields “left” and “right”. Then they can later be projected as necessary. QScript has to handle these magical names.

In QScript, we prefer to handle this situation by having a `JoinFunc` in join nodes that contains an expression representing how the left and right sides of the join should be combined.

**Comment by alissapajer** [comment]
Related to #1539 in that an improved representation of the combine func in logical plan will also be a useful as a representation of the join condition.

**Comment by alissapajer** [comment]
This ticket will be complete when we have a first  class representation of joins in `LogicalPlan`. This ticket is not a high priority and so will be put off until later.
