### ISSUE TITLE
Make use of MarkLogic aggregation facilities for reductions

### ISSUE THREAD

**Issue by wemrysi** [precog/quasar#1626]
Take advantage of the various `cts:*` apis for reductions in order to take advantage of indexes.

Should we fallback to the current impl if no index is defined? Or just error with information on which indexes the user should define?

[SQL's "Group By" the MarkLogic way](https://developer.marklogic.com/blog/group-by-the-marklogic-way) looks like a good place to start.

**Comment by sellout** [comment]
Yes – fallback if no index is defined. We shouldn’t ever error if we don’t have to. I’m working on finally weaving warnings through, so we’ll be able to message non-fatal stuff, like lack of indices.

**Comment by wemrysi** [comment]
Some effort to identify which types of aggregations we can optimize will be required, straightforward field aggregations should be easiest, I'm not yet sure if aggregations of/over computed values can benefit from the aggregation facilities.
