### ISSUE TITLE
Investigate if the way average is being calculated on spark connector does not loose precision

### ISSUE THREAD

**Issue by EncodePanda** [precog/quasar#1689]
Details in https://github.com/quasar-analytics/quasar/pull/1660#discussion-diff-86447144R221

**Comment by sellout** [comment]
Yeah, this change _should_ be trivial, I think – just gotta change `Data.Arr(List(Data.Dec(s1 + s2), Data.Int(c1 + c2)))` to `Data.Arr(List(Data.Dec((s1 * c1 + s2 * c2) / (c1 + c2)), Data.Int(c1 + c2)))` and remove the division from the post-processing (but still need the post-processing to throw away the count).

The trick is figuring out how it affects performance and precision 😄
