### ISSUE TITLE
support for SQL RAND() function

### ISSUE THREAD

**Issue by dashaub** [precog/quasar#1719]
Are there plans on the roadmap for adding the `RAND()` or `RANDOM()` functions? This is particularly useful for data exploration to select a small sample for exploration, e.g. `SELECT * FROM mytable ORDER BY RANDOM() LIMIT 100`.

**Comment by sellout** [comment]
I think this is useful in itself, but there is also #1710 to explicitly support sampling, which I think could be exposed in SQL² akin to `limit`: `select * from mytable sample 100`. So keep an eye on that one, too.
