### ISSUE TITLE
Trim bloat from assembly JARs

### ISSUE THREAD

**Issue by jdegoes** [precog/quasar#1731]
Our JAR sizes have grown almost uncontrollably over time. We should use a tool to shrink them by removing classes that are never in fact used.

**Comment by nicflores** [comment]
A little clarification. Please feel free to correct me if this isn't correct.

We are looking to minimize the sizes of the following jars we publish from the Quasar source.

```
quasar-repl-assembly-<version#>.jar
quasar-web-assembly-<version#>.jar
sparkcore.jar
```

In my first pass at this issue, I experimented with `sbt-proguard`. Using a basic config for `sbt-proguard` I managed to get the web assembly jar minimized from `159M` to `3.8M`.

```
-rw-r--r--  1 nicandroflores  staff   3.8M May  9 23:10 /github/quasar/target/scala-2.11/proguard/root_2.11-17.0.0.jar

-rw-r--r--  1 nicandroflores  staff   159M May  9 15:18 /quasar/.targets/web/scala-2.11/quasar-web-assembly-17.0.0.jar
```

There still a bit more work to get `sbt-proguard` fully incorporated into our build, but this looks promising.

**Comment by jdegoes** [comment]
Wow! Will be impressed if we can get it that low. Hugely important work!
