### ISSUE TITLE
`Id` Func should be removed from LogicalPlan

### ISSUE THREAD

**Issue by sellout** [precog/quasar#1758]
`Id` wraps a Mongo-specific notion of object ID. This should be eliminated, and for queries to submit connector-specific data types, a query should be written like
```sql
select bar @ { "ejson:type": "_.bson.oid" } from objectids
```
(this is from “fakeObjectId.test” which converts a string to a MongoDB OID)

**Comment by jdegoes** [comment]
Related: connector-specific functions.

**Comment by sellout** [comment]
@jdegoes Is there supposed to be a link in there?

**Comment by jdegoes** [comment]
No, but there's supposed to supposed to be a link. :smile:
