### ISSUE TITLE
MongoDB: Encode unsupported EJson values.

### ISSUE THREAD

**Issue by sellout** [precog/quasar#1810]
We can’t store things like metadata and maps with arbitrarily-typed keys (etc.) in MongoDB directly, so we need to encode/decode them when we come across them. Perhaps something like

```json
{ "_ejson:map": [
    [123,                                                              "integer key"],
    [{"_ejson:metadata": { "value": "some key", "metadata": "yup" } }, "key with metadata"],
    ...]
}
```

**Comment by jdegoes** [comment]
In backends that support runtime serialization to/from strings, we can also encode maps as string-keyed maps where the strings are the serialized versions of the arbitrary data values. Assumes serialization is normalized, of course, but allows very fast lookups, groups, etc.

**Comment by sellout** [comment]
I think we should keep in mind that users might look at the resulting data from outside Quasar, so we should choose an encoding that is at least somewhat readable. Also, we sometimes make temp collections, which we immediately, and perhaps it’s worth having a different encoding there that biases toward fast processing vs readability.

Also, we’ll need to do something similar on other connectors, so I suggest we can document some “principles” for these encodings that we can apply across connectors, even though the specific encoding will likely be different (due to different subsets of types and values that are supported natively, different characters available in identifiers, etc.).
