### ISSUE TITLE
Support creation of ranges

### ISSUE THREAD

**Issue by jdegoes** [precog/quasar#1839]
SQL<sup>2</sup> has no way to create ranges yet for numerical and temporal values.

There is some missing SQL<sup>2</sup> syntax for [integral ranges](https://slamdata.atlassian.net/browse/SD-1014?jql=text%20~%20%22range%22) that is not yet supported. With appropriate conversion functions from integers and various dates/times, this facility should work for other types. However, it won't be that user-friendly, so I suggest that we support another function modeled after PostgreSQL, and then implement that function through compilation to integral ranges and conversion functions.

That PostgreSQL function is called [GENERATE_SERIES](https://www.postgresql.org/docs/9.1/static/functions-srf.html), and it can generate a variety of series using user-defined step increments. To the extent that we can, we should replicate their semantics, but it's worth noting the primary use case for the purpose of this ticket is [supporting time/date filling](https://github.com/slamdata/slamdata/issues/1296), and therefore common temporal ranges are the most critical.

- [ ] Add support for SQL<sup>2</sup> range syntax.
- [ ] Add support for generating integral ranges.
- [ ] Add appropriate time/date conversions to and from integral ranges (if missing).
- [ ] Add `GENERATE_SERIES` function that is implemented in terms of lower-level, more composable primitives (if possible).

**Comment by sellout** [comment]
Hrmm, I think ranges are supported (only for ints) … although I see them in the SQL parser, but I don’t see any tests for them.

**Comment by jdegoes** [comment]
I think ints is all we need if we have the right conversion functions.

`(1..10) * 10` produces `10, 20, 30, 40, ..., 100`, etc. This seems to be enough to generate time series and date series.
