### ISSUE TITLE
Failed typing and constant folding of empty result set in LP

### ISSUE THREAD

**Issue by alissapajer** [precog/quasar#1914]
In some cases, when we have the empty result set in `LogicalPlan` we fail to properly type this result set as well as to constant-fold the result so that we don't evaluate the query in a backend. See example below.

**Comment by alissapajer** [comment]
Also of interest:
```
💪 $ select * from (:foo) as f join (:bar) as b on f.a = b.c
Rewritten Joins:
Let('__tmp0)
├─ Invoke(InnerJoin)
│  ├─ Constant(Obj(Map(a -> Int(1), b -> Int(2), c -> Int(3))))
│  ├─ Constant(Obj(Map(a -> Int(7), b -> Int(1), c -> Int(5))))
│  ╰─ Invoke(Eq)
│     ├─ ObjectProject(Obj(Map(a -> Int(1), b -> Int(2), c -> Int(3))){"a"})
│     ╰─ ObjectProject(Obj(Map(a -> Int(7), b -> Int(1), c -> Int(5))){"c"})
╰─ Invoke(Take)
   ├─ Invoke(Squash)
   │  ╰─ Let('__tmp1)
   │     ├─ ObjectProject('__tmp0{"right"})
   │     ╰─ Typecheck(Obj(Map[], Some(Top)))
   │        ├─ Free('__tmp1)
   │        ├─ Let('__tmp2)
   │        │  ├─ ObjectProject('__tmp0{"left"})
   │        │  ╰─ Typecheck(Obj(Map[], Some(Top)))
   │        │     ├─ Free('__tmp2)
   │        │     ├─ Invoke(ObjectConcat)
   │        │     │  ├─ Free('__tmp2)
   │        │     │  ╰─ Free('__tmp1)
   │        │     ╰─ Constant(NA)
   │        ╰─ Constant(NA)
   ╰─ Constant(Int(11))

Quasar error: The back-end has no representation for the constant: Set(List())
```
Same query but with a modified join condition.

**Comment by sellout** [comment]
So, re: the second bug – it’s good that the backend has no representation for `Data.Set`, but there are two problems I see: 1. where is the empty set even coming from, and 2. what bits of constant folding are missing in LP to allow that query to get to a connector?

**Comment by alissapajer** [comment]
The `QScript` looks correct to me in the second bug. @sellout were you suggesting that the query in the second bug shouldn't get to a connector because the query is somehow invalid? Because I think that it is a valid query that should just return the empty set.

I'm thinking that in the first bug we are getting `b` that represents the field name and `b` that represent `:bar` confused, which is what led me to try the second query.

**Comment by sellout** [comment]
Oh, heh, right – I “evaluated” the second query in my head using the condition from the first (i.e., I was expecting a result).

But I meant that it shouldn’t get to a connector because it can be statically evaluated. As can the first – so the first should also never get to QScript.

**Comment by alissapajer** [comment]
This is all very weird:
```
💪 $ select * from (:foo) as f join (:bar) as b on f.c = b.b
Rewritten Joins:
Let('__tmp0)
├─ Invoke(InnerJoin)
│  ├─ Constant(Obj(Map(a -> Int(1), b -> Int(2), c -> Int(3))))
│  ├─ Constant(Obj(Map(a -> Int(7), b -> Int(1), c -> Int(5))))
│  ╰─ Invoke(Eq)
│     ├─ ObjectProject(Obj(Map(a -> Int(1), b -> Int(2), c -> Int(3))){"c"})
│     ╰─ ObjectProject(Obj(Map(a -> Int(7), b -> Int(1), c -> Int(5))){"b"})
╰─ Invoke(Take)
   ├─ Invoke(Squash)
   │  ╰─ Let('__tmp1)
   │     ├─ ObjectProject('__tmp0{"right"})
   │     ╰─ Typecheck(Obj(Map[], Some(Top)))
   │        ├─ Free('__tmp1)
   │        ├─ Let('__tmp2)
   │        │  ├─ ObjectProject('__tmp0{"left"})
   │        │  ╰─ Typecheck(Obj(Map[], Some(Top)))
   │        │     ├─ Free('__tmp2)
   │        │     ├─ Invoke(ObjectConcat)
   │        │     │  ├─ Free('__tmp2)
   │        │     │  ╰─ Free('__tmp1)
   │        │     ╰─ Constant(NA)
   │        ╰─ Constant(NA)
   ╰─ Constant(Int(11))

Quasar error: The back-end has no representation for the constant: Set(List())
```
That differs from the query in the first bug again only in the condition, but it still has `b.b`. So `f.a` in the condition causes the `None.get` while `f.c` in the condition causes the `Set` issue.

**Comment by sellout** [comment]
I think the difference is just whether the condition evaluates to `true` or `false`.

**Comment by alissapajer** [comment]
@sellout agreed that that is consistent with what we're seeing.

**Comment by alissapajer** [comment]
And proven with dropping `true` and `false` in place of the join conditions.

**Comment by alissapajer** [comment]
A touch more information about this `Set`:
```
💪 $ select * from (:foo) as f join (:bar) as b on false
Rewritten Joins:
Invoke(Take)
├─ Invoke(Squash)
│  ╰─ Let('__tmp0)
│     ├─ ObjectProject(Set(List()){"right"})
│     ╰─ Typecheck(Obj(Map[], Some(Top)))
│        ├─ Free('__tmp0)
│        ├─ Let('__tmp1)
│        │  ├─ ObjectProject(Set(List()){"left"})
│        │  ╰─ Typecheck(Obj(Map[], Some(Top)))
│        │     ├─ Free('__tmp1)
│        │     ├─ Invoke(ObjectConcat)
│        │     │  ├─ Free('__tmp1)
│        │     │  ╰─ Free('__tmp0)
│        │     ╰─ Constant(NA)
│        ╰─ Constant(NA)
╰─ Constant(Int(11))

Quasar error: [Expected type Obj(Map[], Some(Top)) but found constant value Set(List())]
```

**Comment by sellout** [comment]
Hrmm, that looks like there’s a subtyping issue – I mean, `Set` needs to go away (it’s on our list of 4.2 stuff), but the empty set should end up with Type.Bottom, which should be a subtype of everything …

**Comment by alissapajer** [comment]
`None.get` error now tracked in #1927.

**Comment by alissapajer** [comment]
We need to properly handling constant folding and empty result sets in `LogicalPlan`. To do this we should remove `Data.Set(Nil)` (which happens to align us more with `EJson`).

Currently we detect the empty result set in cases like `Filter(_, false)` (which has type `Bottom`) but then fail to accept `Bottom` or `Const(Set.Data(Nil))` as a valid type for all the invoke typechecks.
