### ISSUE TITLE
Upgrade to Scala 2.12.1

### ISSUE THREAD

**Issue by djspiewak** [precog/quasar#1953]
This is a meta issue to track the chain of dependencies and stuff that we need to address to upgrade to 2.12.  Some of these are relatively easy, some of them are impossible.  Note that upgrading to 2.12 would allow us to use [`-Yinduction-heuristics`](https://github.com/scala/scala/pull/5649), which will greatly accelerate our compilation times (though a cursory glance at our implicit chains indicates a lot of surface area that [won't be affected](https://github.com/djspiewak/quasar/blob/master/connector/src/main/scala/quasar/qscript/Coalesce.scala#L84-L86)).

- [ ] typelevel discipline
- [ ] scoverage
  + This is always tricky, but I'm pretty sure there's a build of scoverage for 2.12
- [ ] rxscala
  + why is this on our classpath?
- [ ] http4s
  + Blocked by #1852, which is marked as fixed, but only because we're on an older http4s
- [ ] doobie
- [ ] matryoska
  + 0.16.4 doesn't have a 2.12 cross-build; I'm assuming later releases do
- [ ] rapture
- [ ] scodec
- [ ] spark
  + oooooh boy…  this is probably a big one
- [ ] jawn
- [ ] simulacrum
- [ ] shapeless-scalacheck

**Comment by drostron** [comment]
The CB project relies on rxscala to smooth interaction with Couchbase's RxJava style client interface.

**Comment by rabbitonweb** [comment]
Apache Spark is a pain :( Not likely to happen soon.

**Comment by rabbitonweb** [comment]
Targeted version `2.3.0` https://issues.apache.org/jira/browse/SPARK-14220 which means not less then 4 months from now

**Comment by sellout** [comment]
The other big plus with this upgrade is getting better exhaustivity checking. I know we have a number of inexhaustive matches because of extractors/guards that silently break exhaustivity. I’ve removed some extractors (with more to go), but without any word from the compiler, it’s impossible to know that you’ve actually covered everything.

**Comment by sellout** [comment]
@djspiewak If we can get most dependencies updated to versions that have 2.11 & 2.12, we can at least _locally_ take advantage of 2.12 for parts of the tree (e.g., to check exhaustiveness).

And more motivation to break things into separate repos – we can cross-build most of them, and just have sparkcore and whatever else only build on 2.11.

**Comment by djspiewak** [comment]
@sellout Yeah I'm going to work toward this incrementally.  To your second point though, we would still need to cross-build to 2.11, largely negating the advantages of being on 2.12 in the first place (at least from a CI standpoint) since, ultimately, the backends have to be bundled back together for distribution.  So as long as we have that requirement, all of the backends need to be on the same Scala version as the rest of quasar.

**Comment by sellout** [comment]
Right, we’d need to cross-build, but we’d gain the improved exhaustivity in CI. Yeah, it wouldn’t speed up builds, but it would improve correctness. And I think we want to cross-build on 2.11 anyway, since we want to make Quasar (the “interface” subproject) available as a library dependency.

**Comment by djspiewak** [comment]
@sellout Oh, sidebar: it's actually possible to locally build different subprojects with different Scala versions, it's just not done very often.  In order to make it work, dependent projects would need to be cross-built, but it's a path to achieve the cross-build vision before polyrepo.
