### ISSUE TITLE
Extend and apply linearized `Coproduct` encoding

### ISSUE THREAD

**Issue by djspiewak** [precog/quasar#1984]
I'm relatively certain that a significant chunk of our current compilation inefficiencies comes from the binarized nature of the `Coproduct` encoding.  This is something that I feel could be fixed upstream (i.e. in cats) with a nicer `Coproduct` in the style of FreeK which is both easier to use and faster to compile.

For context, symmetric binarized type constructors (like `Coproduct`) necessitate extremely problematic implicit derivations (such as [this one](https://github.com/djspiewak/quasar/blob/master/connector/src/main/scala/quasar/qscript/Coalesce.scala#L111-L115)), which increase the *k* factor in the compiler's *O(k^n)* implicit resolution algorithm.  Linearized data constructors (such as `CoM`) work a lot more effectively, since the compiler only has to falsify a single tree branch, rather than two.

Additionally, construction can be made more amenable to nominative falsification, which is to say a situation where the compiler has only a single candidate solution for free type variables, and can validate that solution by nominative type tests, rather than having to attempt various shape instantiations (potentially spanning multiple levels of the implicit search hierarchy).  This is effectively how backtracking is encoded in implicit search, and it is easier to more aggressively avoid it with linear encodings.

**Comment by edmundnoble** [comment]
I think the best answer to this as it stands now is https://github.com/frees-io/iota, which has zero dependencies and provides a nominally-right-associated performant coproduct. This should speed up compilation and runtime performance of code that touches coproducts quite a bit, especially QScript.

**Comment by djspiewak** [comment]
I think Iota is a sufficiently promising solution that this is worth devoting a few developer days to in the near future.  I'll see if I can squeeze it in.

**Comment by rintcius** [comment]
Note: since v0.3.1 iota has scalaz support https://github.com/frees-io/iota/releases/tag/v0.3.1
