### ISSUE TITLE
Ability to specify timezone in query

### ISSUE THREAD

**Issue by damonLL** [precog/quasar#1985]
Request for enhancement to specify timezone in query, instead of the default GMT / Zulu.

Example would be to group by date using CST instead of GMT/Zulu.

The workaround now might be to use `INTERVAL` like:

```
💪 $ select first_name, last_name,last_visit,  (last_visit - INTERVAL("PT5H")) as US_East, (last_visit - INTERVAL("PT6H")) as US_Central from patients
Query time: 0.1s
 first_name | last_name  | last_visit            | US_East               | US_Central            |
------------|------------|-----------------------|-----------------------|-----------------------|
 Jude       | Wilkerson  |  2013-04-08T08:07:42Z |  2013-04-08T03:07:42Z |  2013-04-08T02:07:42Z |
 Theo       | Joseph     |  2014-09-22T10:15:40Z |  2014-09-22T05:15:40Z |  2014-09-22T04:15:40Z |
 Grisel     | Branch     |  2012-09-06T15:20:25Z |  2012-09-06T10:20:25Z |  2012-09-06T09:20:25Z |
 Ollie      | Shepherd   |  2015-05-08T09:09:42Z |  2015-05-08T04:09:42Z |  2015-05-08T03:09:42Z |
 Jonathan   | Riley      |  2016-01-16T13:14:34Z |  2016-01-16T08:14:34Z |  2016-01-16T07:14:34Z |
 Vaughn     | Wilkins    |  2013-11-22T11:17:21Z |  2013-11-22T06:17:21Z |  2013-11-22T05:17:21Z |
 Kayla      | Bradshaw   |  2007-04-22T14:00:29Z |  2007-04-22T09:00:29Z |  2007-04-22T08:00:29Z |
 Devon      | Jensen     |  2016-10-13T13:37:47Z |  2016-10-13T08:37:47Z |  2016-10-13T07:37:47Z |
 Jean       | Santiago   |  2013-08-31T08:59:46Z |  2013-08-31T03:59:46Z |  2013-08-31T02:59:46Z |
 Mee        | Shaw       |  2006-11-11T12:35:20Z |  2006-11-11T07:35:20Z |  2006-11-11T06:35:20Z |
```

Is there a better / more standardized way of doing this?  The example above would not survive daylight savings transitions and would need to be updated twice a year.

**Comment by jdegoes** [comment]
I am not sure exactly what you are asking for. Can you find equivalent functionality in Postgres so we can simply replicate the corresponding Postgres function?

**Comment by damonLL** [comment]
@jdegoes, something like `AT TIME ZONE` ?  [Postgres Example](https://www.postgresql.org/docs/9.2/static/functions-datetime.html#FUNCTIONS-DATETIME-ZONECONVERT)

**Comment by jdegoes** [comment]
@damonLL That looks good to me. Is this for paying customer, demos, prospects, or a user?

**Comment by damonLL** [comment]
@jdegoes paying customer

**Comment by jdegoes** [comment]
@zeeiyerWork Let's get this into the June milestone.

**Comment by edmundnoble** [comment]
It's looking like this will be possible after the solution to #2564, though there will need to be extra work to add syntax to SQL^2 for it.
