### ISSUE TITLE
epic: Connector: Joins within Marklogic

### ISSUE THREAD

**Issue by zeeiyerWork** [precog/quasar#2078]
This epic is a container for all issues related to Joins within Marklogic

**Comment by alissapajer** [comment]
It looks like this epic has just one issue housed under it (#1505). As such, I think it would make sense to house #1505 in another ML epic. If ML joins turn out to require multiple issues, we could make an epic for it then.

**Comment by djspiewak** [comment]
…or alternatively, #1505 could just not be assigned to an epic at all.  No need to impose extra hierarchy before it is needed.
