### ISSUE TITLE
Run planner tests across all versions.

### ISSUE THREAD

**Issue by sellout** [precog/quasar#2126]
Right now our planner tests run only against 3.2 unless we explicitly call `plan3_0`, etc. But to catch variations between versions, we should do something like:
```scala
"plan foo" in {
  plan("select * from foo") {
    case (3, 2) => $read(???)
    case (3, 0) => ???
    case (_, _) => ???
  }
}
```
and always run all queries against all versions.

**Comment by jdegoes** [comment]
Except with bounded natural numbers and not integers. 😆
