### ISSUE TITLE
Simplify handling of “date_part” for connectors.

### ISSUE THREAD

**Issue by sellout** [precog/quasar#2169]
Currently there are 21 `Extract` MapFuncs that connectors need to handle, but many of these are simply SQL-isms that we shouldn’t propagate through.

Some thoughts on what we can do:
1. switch to a single function (`TemporalPart`?) with an enumeration like `TemporalTrunc`;
2. rename `IsoDayOfWeek` to `DayOfWeek` and `IsoYear` to `YearOfWeek`;
3. remove `Epoch`, making it a separate function like `ToEpoch`;
3. eliminate `Century`, `DayOfWeek`, `Decade`, `Microseconds`, `Millennium`, `Milliseconds`, and `Quarter` (defining them in terms of the remaining extractors either in the SQL² compiler or via some stdlib of parameterized views – this may require); and
4. eliminate the non-“standard” SQL calls, like `extract_timestamp_hour(date)` in favor of `date_part("timestamp_hour", date)`.

Things I’m still waffling on:
* in my proposed formulation, they all return integers _except_ `Second`. If `TemporalPart` is restricted to integers, then we probably need to keep `Milliseconds` and `Microseconds`
* can we somehow share an enumeration with `TemporalTrunc`? `-Trunc` has some components we’re getting rid of (like `Century`), and `-Part` has multiple notions with the same precision (like `DayOfYear` and `DayOfMonth`), so there’s some conflict, but maybe we could do use a type like `(TemporalPrecision, DateFormat)` for the `-Part` parameter where `DateFormat` indicates which of the ISO formats we’re using, but then `(Month, Ordinal)` doesn’t make sense, because there’s no months in the ordinal format.

**Comment by zeeiyerWork** [comment]
@sellout - Does @djspiewak merge #2172 resolve this fully or partially. Based on that please add a comment and leave this open or close it. Thanks.

**Comment by sellout** [comment]
@zeeiyerWork Nope – that PR is related to SQL², this issue is about QScript.

**Comment by zeeiyerWork** [comment]
More of an improvement - so will be scheduled for later.
