### ISSUE TITLE
Revisit error message format produced by the various API endpoints

### ISSUE THREAD

**Issue by kritzcreek** [precog/quasar#2175]
The error response we get from Quasar outlined in https://github.com/slamdata/purescript-quasar/issues/36 is somewhat unfortunate. The `error.status` field is misleading, and one needs to get at `error.detail.reasons` which seems to be somewhat arbitrary to parse.

Could we either provide a proper human-readable error message at `error.detail.message` or use the `MultipleErrors` format (https://github.com/slamdata/purescript-quasar/issues/37) if we need to keep the array around?
/cc @garyb

**Comment by jedesah** [comment]
```json
{
  "summary": "Cannot read from file: `/foo/bar` because it does not exist",
  "tag": "FileNotFound",
  "details": {
    "file": "/foo/bar"
  }
}
```

summary: User readable summary of error
