### ISSUE TITLE
Operations in a `CASE ... WHEN` can also affect results where the case does not match

### ISSUE THREAD

**Issue by garyb** [precog/quasar#2180]
This occurs on the old Mongo connector, but not sure if it is connector specific or whether there's something else wrong here.

With this test data:

``` json
{ "b": { "ba": true, "bb": ["x", false, { "foo": "bar" }], "bc": 0.5 } }
{ "b": [1, 2, 3] }
{ "b": "test flat value" }
```

And this query:

``` sql 
SELECT
    CASE TYPE_OF(t.b)
    WHEN "map" THEN t.b{*}
    WHEN "array" THEN ARRAY_LENGTH(t.b, 1)
    ELSE t.b END as b
FROM
    `/test/flatten_test.json` as t
``` 

The result is:

``` json
[
{  },
{  },
{  },
{ "b": 3 },
{  }
]
```

Something is definitely wrong here, as it looks like the map was flattened (in that there are 3 empty objects returned before the `b: 3`), but then it discarded the contents of those results anyway.

The last object being empty is possibly sensible, as `TYPE_OF` returns `"array"` for strings, but `ARRAY_LENGTH` does not operate on them.

This also occurs for `UPPER`, `LOWER`, etc.

It seems like there may be a problem with how the result is dealt with when it is a literal, as wrapping the case result in a map restores the values in the other objects:

``` sql
SELECT
    CASE TYPE_OF(t.b)
    WHEN "map" THEN t.b{*}
    WHEN "array" THEN { "x": ARRAY_LENGTH(t.b, 1) }
    ELSE t.b END as b
FROM
    `/test/flatten_test.json` as t
```

Results in:
``` json
[
{ "b": true },
{ "b": [ "x", false, { "foo": "bar" } ] },
{ "b": 0.5 },
{ "b": { "_id": { "$oid": "59132f2169e88253c2a3f158" }, "x": 3, "__tmp4": true, "__tmp5": [ 1.0, 2.0, 3.0 ], "__tmp10": { "__tmp7": { "_id": { "$oid": "5912f4af74557d23aeef927d" }, "b": [ 1.0, 2.0, 3.0 ] } } } },
{ "b": { "_id": { "$oid": "59132f2169e88253c2a3f15a" }, "__tmp4": true, "__tmp5": "test flat value", "__tmp10": { "__tmp7": { "_id": { "$oid": "5912f4af74557d23aeef927e" }, "b": "test flat value" } } } }
]
```

**Comment by zeeiyerWork** [comment]
@sellout -> Seems like we need a clarification as to whether this is old-mongo artifact or a deeper issue that straddles the various mongo-connector implementations

**Comment by zeeiyerWork** [comment]
Next step is to understand whether something is going wrong in the conversion of the LP to QScript. @alissapajer  will take a look and report back.

**Comment by alissapajer** [comment]
Assigned this to myself as well so it's on my radar.

**Comment by zeeiyerWork** [comment]
@jsantos17 -> please work with @alissapajer on this one.
@rintcius -> fyi, reassigned to @jsantos17, since he has a little more room than anticipated.

**Comment by jsantos17** [comment]
This looks broken in `next-major`.

```sql
💪 $ SELECT * FROM `/mngo/jps/flatten_test`
```

```
Query time: 0.0s
{ "b": { "ba": true, "bb": [ "x", false, { "foo": "bar" } ], "bc": 0.5 } }
{ "b": [ 1, 2, 3 ] }
{ "b": "test flat value" }
```
Data is there, running the query provided by @garyb yields three empty objects:

```sql
💪 $ SELECT 
    CASE TYPE_OF(t.b) 
      WHEN "map" THEN t.b{*} 
      WHEN "array" THEN ARRAY_LENGTH(t.b, 1) 
      ELSE t.b END as b FROM `/mngo/jps/flatten_test` as t
```

```
Query time: 0.4s
{  }
{  }
{  }
```

The same query using the Marklogic connector (both JSON and XML) results in:

```json
{ "b": true }
{ "b": [ "x", false, { "foo": "bar" } ] }
{ "b": 0.5 }
{ "b": 3 }
{ "b": 3 }
{ "b": 3 }
```

which is presumably the correct result. So it seems unlikely this is a bug in QScript since it works fine in a different QScript-based connector.

**Comment by garyb** [comment]
I'm not sure that result is correct either, although it's certainly a lot more like it! The fact there's 3x`{ "b": 3 }` seems a little odd?

**Comment by jsantos17** [comment]
Indeed seems fishy. I'll do some more research and see if I figure out the correct result. But yeah, this looks broken in `next-major` and in old Mongo.

**Comment by garyb** [comment]
It doesn't help that the query is bananas and not the kind of thing anyone would do in the real world... probably 😆
