### ISSUE TITLE
Most recent value problem

### ISSUE THREAD

**Issue by amitbed** [precog/quasar#2189]
Hi,
I'm using mongodb, and I have a table called xTable that have attributes X and TimeM.
TimeM - is a timestamp.
X - A number.

I tried to perform the above query (sql2):

`SELECT X, TimeM 
FROM /xxx/db/xTable
WHERE TimeM = MAX(TimeM)`

I also tried this query:

`SELECT X, MAX(TimeM)
FROM /xxx/db/xTable`

and I get an empty set, although this collection has many documents with this attributes.

I posted this question here: 
[https://groups.google.com/forum/#!topic/slamdata-user/uPPfyz_FSvg](url)
and they told me that it might be a bug on quasar.

**Comment by damonLL** [comment]
@amitbed can you please provide the MongoDB query that Quasar is generating, as requested in the slamdata-user group?  The latest REPL console is [here](https://github.com/quasar-analytics/quasar/releases/download/v16.1.6/quasar-repl-assembly-16.1.6.jar)  From the console type `SET DEBUG = 1` then run your query, it should provide the MongoDB query for you.

**Comment by amitbed** [comment]
Thank you for your answers.
@sellout TimeM is a MongoDB timestamp.
@damonLL  How do I start the console? I looked at the instructions here:
`https://github.com/quasar-analytics/quasar`
and couldn't execute `./sbt 'repl/assembly'`

**Comment by sellout** [comment]
Ok, the simple fix here is to include BSON Timestamps in the guards for Quasar Timestamps. This isn’t strictly correct, but it should give expected behavior on Mongo.
