### ISSUE TITLE
Test of commutativity of product Types failed

### ISSUE THREAD

**Issue by wemrysi** [precog/quasar#2194]
Seen on Travis for f56b2f9 in `TypesSpec.scala`
```
[info] product should
[error] x have order-independent equality for arbitrary types (253 ms)
[error]  Falsified after 74 passed tests.
[error]  > ARG_0: Const(Obj(Map($date -> Str(Jan 1))))
[error]  > ARG_1: Coproduct(Const(Obj(Map($date -> Str(Jan 1)))),Const(NA))
[error]  > constant value Obj(Map($date -> Str(Jan 1))), or constant value NA !== constant value Obj(Map($date -> Str(Jan 1)))
```

**Comment by zeeiyerWork** [comment]
@wemrysi  -> Do we still see this or has it disappeared into the ether or has it been explicitly resolved?  If it is a transient Travis issue, perhaps we close it out and reopen if we see it again?

**Comment by wemrysi** [comment]
I haven't seen the failure again, but I doubt it is because it has been fixed, more likely that the particular combination of arguments necessary to cause it haven't been generated by scalacheck since. I'd leave it open.

**Comment by rintcius** [comment]
@zeeiyerWork @wemrysi coincidently It's just spotted in #2601 (looks like this spec is only running once overall, so assuming it's the same failure)

**Comment by alissapajer** [comment]
Same test failure seen again, this time with the `NA` on the other side of the coproduct:
```
[error] x have order-independent equality for arbitrary types (147 ms)
[error]  Falsified after 68 passed tests.
[error]  > ARG_0: Coproduct(Const(NA),Const(Obj(Map($date -> Str(Jan 1)))))
[error]  > ARG_1: Const(Obj(Map($date -> Str(Jan 1))))
[error]  > constant value Obj(Map($date -> Str(Jan 1))) !== constant value NA, or constant value Obj(Map($date -> Str(Jan 1))) (QuasarSpecification.scala:51)
```
