### ISSUE TITLE
Confusing error when MetaStore is already in use.

### ISSUE THREAD

**Issue by sellout** [precog/quasar#2299]
I just ran `repl/run` and got “Error: While verifying MetaStore schema: Exception during pool initialization. Is the metastore database running?”

I was wondering how I could manually start the metastore, but the problem was actually that I already had a repl running, and I’m guessing I can only have one connection to it at a time?

**Comment by drostron** [comment]
There can only be one instance running against an H2 based metastore at the moment. We should at least offer an improved error or extend the H2 flavor to support more than one instance.

**Comment by zeeiyerWork** [comment]
@drostorn -> As you highlighted, please provide a friendlier and actionable error message and we can then close it out.
