### ISSUE TITLE
Server side Caching Control

### ISSUE THREAD

**Issue by zeeiyerWork** [precog/quasar#2325]
- [ ] Document and Simplify REST APIs to Prime And Clear any given Server-side cache.
- [ ] Add a REST API to provide system wide caching in Play - i.e. expose the backend caching metadata table contents:
- Cache Path (i.e. path of the materialization).
- Time to Prime 
- Last Update Time
- Next Update Time
- TTL
- Cache Hit Ratio (i.e. how many reads off cache).
- While it would be useful to know which Cache is referenced in which decks, that information is possibly available only on the front-end and would not make sense to include here.

@drostron and @jedesah - please comment if any other suggestions and thoughts.

**Comment by jdegoes** [comment]
We do not have any customer requests for these features. They are quite useful but let's wait for now as we have so much other stuff to work on (and also we would ideally do UI support rather than just a simple REST API).

**Comment by zeeiyerWork** [comment]
The thinking was the following:
1. The REST APIs to prime and clear the cache already exist. It is just about cleaning these up - when a deck computation references a cache-card, it translates to a REST call to prime the cache if the cache isn't already primed. 
2. The table that stores all this data already exists. Again its just a question of exposing it. Hence the thought of a REST API to highlight it. The UI could presumably be an advanced feature (i.e. in slamdata-advanced).
3. These capabilities, IMHO, are integral to even a MVP implementation of a cache. 
- i.e. being able to clear/prime cache based on operational events as against always waiting on a predetermined TTL, which could not have predicted operational events.
- Cache hit ratio (to determine if caching something was even worth it in the first place).

A look at the simplest cache implementations in the wild can verify this point of view. I suppose that is where the disagreement appears - is this MVP or MVP++, in which case, we wait for customer feedback to pull? - Seems like your call is the latter. Correct? Plz clarify. If you still feel that way, will move out of August milestone.

**Comment by jdegoes** [comment]
These functions will not be used without a front-end interface. Indeed, a user can simply query the backing database (H2/Postgres) to find out much of this information or perform changes manually, the addition of a REST API does not make any of this substantially simpler.

For this reason, I prefer to push out until we have people using the cache — validating that it's a useful approach to caching — and asking for more admin functionality.

**Comment by zeeiyerWork** [comment]
OK, will move it to the backlog, especially given other higher priorities. Yes there is a way for now, although it requires knowledge of quasar implementation details (table name, schema etc.) - so it's a subjective judgement call on how courteous we want to be to the "author"/"admin" - given that:
- UI >> (much much better than)
- REST-API (Standard way of interacting with *any* server-side) >> 
- Having to know implementation details of a given server-side implementation.

Also, if we do support 3rd party caches (in the use-case where what is being cached is the terminal card in the deck and no further computation is required), then these functionalities are available for free e.g.
- [Ehcache](http://www.ehcache.org/documentation/3.3/), 
- [Statistics for Terracotta Server Array](http://terracotta.org/documentation/4.1/tms/tms-rest-api#statistics) 
- [Memcache](https://github.com/memcached/memcached/wiki/Commands#statistics) 
- etc.
