### ISSUE TITLE
Same SQL^2 query returns different results

### ISSUE THREAD

**Issue by Cmdv** [precog/quasar#2345]
### Description

Uploading the same olympics.json file and running the same queries against different Databases yields different results

### Reproduction guide

`mount database` couchbase -> create workspace -> `markdown card` create query:
```
discipline = __ (!``SELECT discipline FROM `/test-mount/olympics.json` LIMIT 1``)

year = __ (!``SELECT year FROM `/test-mount/olympics.json` LIMIT 1``)

country = {!``SELECT DISTINCT country FROM `/test-mount/olympics.json` ``} (!``SELECT country FROM `/test-mount/olympics` LIMIT 1``)

type = (!``SELECT DISTINCT type FROM `/test-mount/olympics.json` LIMIT 1``) !``SELECT DISTINCT type FROM `/test-mount/olympics.json` OFFSET 1``

gender = [!``SELECT gender FROM `/test-mount/olympics.json` LIMIT 1``] !``SELECT DISTINCT gender FROM `/test-mount/olympics.json` ``
```
### Results

**Couchbase:**
<img width="363" alt="screen shot 2017-06-17 at 00 48 45" src="https://user-images.githubusercontent.com/3036557/27248106-2c7928ea-52f7-11e7-8cb6-f1f77740c5a5.png">

**Marklogic:**
<img width="369" alt="marklogic" src="https://user-images.githubusercontent.com/3036557/27248240-b1fe616e-52f8-11e7-8baf-5588e3886efe.png">

**MongoDB:**
<img width="388" alt="mongo" src="https://user-images.githubusercontent.com/3036557/27248176-e0e86462-52f7-11e7-9455-74e5129fceb5.png">

**Observed behaviour:**

The type(medal) is different for all 3 databases.
This behaviour is seen when performing further queries on continuation of test.

... -> query card -> pivot table -> display table -> lots of variations between databases

query:
```
SELECT * FROM `/test-mount/olympics.json` WHERE discipline = :discipline AND type != :type AND gender IN :gender AND year > :year AND country = :country
```

**Comment by alissapajer** [comment]
So it looks like the three queries are returning the same results, it's just that the values of `type` are displayed in a different order for each backend, and so there is a different default value selected per query. You should be able to select "Gold" for all three queries and see that further cards produce the same results.

Furthermore in your query for assigning the variable `type` you are not specifying an ordering for the return values, so any return order of the values is correct. What I'm not sure about is if the frontend would/should preserve the order (if there were an order in the query) in the radio buttons. If it's important that the values of `type` are displayed in the same order for each backend, then that sorting is something the frontend would have to take care of (assuming no sorting in the original query).

**Comment by Cmdv** [comment]
@alissapajer do you think that maybe there is a way that I could extend the query to get the same results across all databases?

**Comment by jdegoes** [comment]
@Cmdv Order the result set by using `ORDER BY`. This will give you deterministic ordering.

**Comment by wemrysi** [comment]
@jdegoes Indeed it should, but I don't think it will, in general, until #1882 is implemented.

**Comment by sellout** [comment]
@wemrysi Yeah, you’re right. That’s fixed on the new Mongo branch (I know, broken record).

But at least once the frontend adds `order by`, it becomes a backend issue. Until then, it’s still their problem 😄

**Comment by Cmdv** [comment]
@jdegoes , @wemrysi thanks
@sellout I'll be back soon to pass the baton back 😛 

feel free to close unless you want this as a reference 😄
