### ISSUE TITLE
SST time values are turned into strings

### ISSUE THREAD

**Issue by garyb** [precog/quasar#2355]
From some test data like this:

``` json
{ "testTime": { "$time": "10:23:54" } }
{ "testTime": { "$time": "12:23:54" } }
```

The returned structure is:

``` json
            "testTime": {
                "measure": {
                    "count": 2,
                    "min": "10:23:54.000",
                    "max": "12:23:54.000",
                    "minLength": 12,
                    "maxLength": 12
                },
                "structure": {
                    "type": "array",
                    "of": {
                        "measure": {
                            "count": 2
                        },
                        "structure": {
                            "type": "character"
                        }
                    }
                }
            }
```

They definitely were time values at some point, as `.000` milliseconds has been appended! :smile:

**Comment by sellout** [comment]
I _think_ this is a Mongo-specific problem, as we encoded times as strings before we had a better way. If you can try this on another connector and add the Mongo label if it works fine there.

Additionally, this _might_ have the same problem as #2354 where we want `"_ejson.string"` somewhere in it?

**Comment by garyb** [comment]
@sellout looks like you're right, I tested with spark local and it gives me a map.
