### ISSUE TITLE
Invoke endpoint parameters can shadow function arguments

### ISSUE THREAD

**Issue by wemrysi** [precog/quasar#2367]
Currently, the additional parameters to the invoke endpoint, `limit` and `offset` can shadow any module function arguments of the same name.

```
curl -X PUT -H "Content-Type: application/json" --data-binary '{"module": "create function offset(:limit) begin 10 + :limit end"}' http://localhost:20223/mount/fs/mod1/
>>> added /mod1/

curl http://localhost:20223/invoke/fs/mod1/offset\?limit\=0
>>> { "error": { "status": "Invalid query parameter.", "detail": { "message": "invalid limit: 0 (must be >= 1)" } } }
```

Maybe function arguments should have their own parameter namespace to separate them from other parameters to the endpoint, something like
```
GET /invoke/some/module/afunction?limit=10&arg.foo=74&arg.bar=quux
```
which sets the endpoint's `limit` parameter to `10` and passes the arguments `foo` and `bar` to the function `afunction`.

**Comment by jdegoes** [comment]
We have another API (somewhere) that uses namespacing. We should try to be consistent with that (or visa versa).

**Comment by wemrysi** [comment]
Indeed, the query endpoint [uses the `var` namespace](https://github.com/quasar-analytics/quasar#get-queryfspathqqueryoffsetoffsetlimitlimitvarfoovalue).
