### ISSUE TITLE
Change handling of IdStatus

### ISSUE THREAD

**Issue by sellout** [precog/quasar#2368]
When `IncludeId` is used, the rest of the QScript query assumes that it is stored as `[id, value]`, and uses `ProjectIndex` to access it. However, this can pessimize queries. For example, in MongoDB, it would be simpler if  the accessor for the id were `ProjectField(HoleF, "_id")` and the accessor for the value were `DeleteField(HoleF, "_id")`.

However, those particular accessors in Mongo only work when it’s the `IdStatus` on `ShiftedRead` – `IdStatus` on `LeftShift` is just fine using the current approach. I.e., collection identity and map keys may have different ways of being accessed efficiently. And it doesn’t help that we may also convert one into the other, e.g., with `ShiftRead`.

**Comment by wemrysi** [comment]
Just to add another data point, this would also benefit MarkLogic in the `ShiftedRead` case as we use the URI of a document as its id and that can be accessed at any time via a function without having to carry it around in an array.
