### ISSUE TITLE
Spark (local) misbehaves when encountering binary values

### ISSUE THREAD

**Issue by garyb** [precog/quasar#2372]
A file like this:
``` json
{ "testBinary": { "$binary": "TE1OTw==" } }
```
Is unopenable / queryable / schema-able on Spark local.

Not sure if that's a known issue or not? I couldn't see any other references to this.

**Comment by rabbitonweb** [comment]
What do you mean by binary values in json ?

**Comment by garyb** [comment]
The example I gave up there is a document with the "precise" JSON encoding for a binary value.
