### ISSUE TITLE
Some intervals cannot be represented in Quasar currently

### ISSUE THREAD

**Issue by garyb** [precog/quasar#2373]
From the discussion in #2356 - intervals are currently represented as a fixed length of time, but the format supports "floating" intervals like `P6M` that can differ depending on start date.

There is a note in the docs, in the precise format examples that states

> Note: year/month not currently supported.

Which I assume refers to this kind of thing, but there does't seem to be an existing issue for it.

**Comment by edmundnoble** [comment]
This will be addressed by the fix to #2564.

**Comment by alissapajer** [comment]
@edmundnoble feel free to reassign yourself. I haven't looked at this at all.
