### ISSUE TITLE
Implement Multi-Version Plumbing

### ISSUE THREAD

**Issue by zeeiyerWork** [precog/quasar#2378]
The idea is to universally implement for the mongo connector - a cascading version implementation. i.e. fall down from latest Mongo version to older Mongo versions to base implementation for a given operator.
It presumably could be applied to other connectors if we are convinced that it works satisfactorily for Mongo.

**Comment by sellout** [comment]
See #2375 and #2376 for the concrete Mongo issues. I’d say this ticket should basically cover the discussion as to whether this is the right approach for all connectors, or if there’s something else we should be doing.

**Comment by jdegoes** [comment]
I was originally going to handle this (way back in 2014) as some sort of explicit lazy data structure, e.g.:

```scala
case class Versioned[A](value: Map[MongoVersion. A])
```

Idea being you can produce in parallel (possibly lazily) different plans in all the junctions that require them. "Selective versioning" since many nodes don't require that variation.

**Comment by rintcius** [comment]
ping @zeeiyerWork - I removed this from `epic: Connector: New Mongo - Initial Production Rollout`

**Comment by zeeiyerWork** [comment]
@rintcius  - why? I thought it was a pre-requisite to the way you were implementing some of the other issues?

**Comment by rintcius** [comment]
@zeeiyerWork Based on @sellout's comment above regarding scope of this ticket.

It's not a pre-req really, I implemented mongo 3.4. plumbing according to current mechanism (which is already a cascading version implementation) and this works fine for now. We _can_ look into improving the mechanism, but I'd say this is lower prio.

**Comment by zeeiyerWork** [comment]
ok sounds good.
