### ISSUE TITLE
Support additional MongoDB Array Operators

### ISSUE THREAD

**Issue by zeeiyerWork** [precog/quasar#2379]
- [ ]  Support $slice — Support as `[foo[0 .. 2] ...]` (requires a change to semantics!)
- [ ]  Support $range — Support as `0 .. 2`
- [ ]  Support $reverseArray
- [ ]  Support $indexOfArray — Support in pattern matching
- [ ]  Support $reduce — Support as ???
- [ ]  Support $zip — Support as `[[foo[_], bar[_]] ...]` or equivalent, and useful when generating array indices
- [ ]  Support $map — Support as ???
- [ ] $arrayElementAt
- [ ] $concatArrays
- [ ] $isArray
- [ ] $filter to avoid map-reduce.
- [ ] $size (as per conversation in #1896)

**Comment by sellout** [comment]
Adding these to ExprOp is fairly simple, but we should add a general QScript transformation for identifying things like `Reduce(LeftShift(<some array>))` and turning them into optional MapFunc components, so connectors can 1. decide whether to support these and 2. not have to identify these patterns themselves.

**Comment by zeeiyerWork** [comment]
@sellout - take it you will create the related ticket on the Qscript/planner end of things....
