### ISSUE TITLE
Push SQL user defined functions and imports into `LogicalPlan`

### ISSUE THREAD

**Issue by jedesah** [precog/quasar#2398]
This will allow us to provide better, earlier error messages when invoking functions, executing queries and mounting views and modules.

Currently, functions are simply inlined at SQL layer which means there is no good way to validate that a function is semantically correct without actually calling that function. If we actually add a representation for functions at the `LogicalPlan` level, we will be able to verify a function body in isolation of any particular arguments it may receive when being invoked.

**Comment by zeeiyerWork** [comment]
@jdegoes , @alissapajer -> can y'all comment on the relative importance of this and hence prioritization.

**Comment by jedesah** [comment]
Another concrete example @natefaubion just brought up is that calling a function with the wrong number of arguments currently yields a "Function Not Found" error which is rather confusing. That's so that user defined functions don't shadow library functions (if they have a different argument, but if user defined functions were in LP, it would make it possible to provide a better error message without shadowing.

**Comment by alissapajer** [comment]
So, this ticket will provide better error messages for the user when using functions. @jedesah are there other specific errors you know of that will be made possible besides the one you just mentioned?

@zeeiyerWork I think the priority of this ticket should be driven by customer needs. When customers need these better error messages then we can get this done. To my knowledge it's not blocking anything from an engineering point of view.

**Comment by jedesah** [comment]
@alissapajer It will also provide earlier compile errors when mounting a module. Currently, it's possible to mount anything that parses, even if it's otherwise complete gibberish. Only when the function is called will we find that out. I recall complaining a few times about functions not being pushed to LP in the discussion when you reviewing my imports PR, but I don't remember everything I complained about 😄 

But I agree that it should be driven by the priority of providing this better experience to the user. If modules are mostly used by the frontend to implement sane sharing of dashboards then I don't think  this is likely to be very visible to users. If, however, users start using functions and modules heavily "manually" to structure their own queries then this is likely to become much more visible and frustrating for them.

It's a little bit of technical debt because we might build around the current implementation, but my prediction is that the interest rate will be very low so I don't think that needs to be an important factor in deciding when to implement this.

**Comment by zeeiyerWork** [comment]
@alissapajer, @jedesah  -> Better error messaging is a business priority - but given how packed current iterations are - scheduling this for a 4.3.x release target (i.e. October iteration)
