### ISSUE TITLE
Couchbase - Not currently mapped to N1QL's key join error

### ISSUE THREAD

**Issue by Cmdv** [precog/quasar#2403]
### Description

Creating a flexible visualisation card eventually returns an error.

### Reproduction guide

mount couchbase -> setup variable card: `name: state` - `type: Text` - `Default Value: CO`
troubleshoot card -> query card:
```
SELECT count(*) as ct, city, gender FROM `/test-mount/patients` WHERE state = :state GROUP BY city, gender ORDER BY ct DESC LIMIT 30
```
barchart card: `category: city` - `Sum: ct` -> ERROR

### Results
`Failed to plan query.: unimplemented EquiJoin: Not currently mapped to N1QL's key join`
<img width="811" alt="screen shot 2017-06-27 at 14 57 15" src="https://user-images.githubusercontent.com/3036557/27610408-21f07fe4-5b86-11e7-9977-3d00fc87b406.png">

**Comment by drostron** [comment]
Currently the CB connector supports the subset of SQL² that's mappable to N1QL's key join.

Related issues: https://github.com/quasar-analytics/quasar/issues/1587, https://github.com/quasar-analytics/quasar/issues/2128, https://github.com/quasar-analytics/quasar/issues/2117

**Comment by Cmdv** [comment]
@drostron cool thanks, I assume linked issues will need completion before this is fix?

**Comment by drostron** [comment]
@Cmdv Not necessarily. To add a little more clarity, hitting that error means the query is resulting in QScript that contains a join. For that to work #1587 would need to be addressed. The alternative would be to address whatever is leading to the join.

**Comment by sellout** [comment]
Yeah, I don’t think there should be a join in this query (although I could be wrong).

**Comment by sellout** [comment]
I.e. – there’s likely a bug in QScript or earlier.

**Comment by alissapajer** [comment]
The join in the qscript is coming from the `count(*)`. Even the query `select count(*) as cnt, state from zips` currently has a join in the qscript. The `LogicalPlan` for this simpler example looks like this:
```
Let('__tmp0)
├─ Let('__tmp1)
│  ├─ Read(/spark/zips)
│  ╰─ Typecheck(Obj(Map[], Some(Top)))
│     ├─ Free('__tmp1)
│     ├─ Free('__tmp1)
│     ╰─ Constant(NA)
╰─ Invoke(Take)
   ├─ Invoke(Squash)
   │  ╰─ Invoke(ObjectConcat)
   │     ├─ Invoke(MakeObject)
   │     │  ├─ Str("cnt")
   │     │  ╰─ Invoke(Count)
   │     │     ╰─ Free('__tmp0)
   │     ╰─ Invoke(MakeObject)
   │        ├─ Str("state")
   │        ╰─ ObjectProject(Free('__tmp0){"state"})
   ╰─ Constant(Int(11))
```
where the problem in qscript is that in order for there not to be a join, we'd need to cleanly merge the `Count` and the `ObjectProject` of `"state"`. @sellout I'm not sure if/how we can do this since the reduction is [affecting the provenance](https://github.com/quasar-analytics/purescript-mra/blob/master/src/MRA.purs#L719).

**Comment by sellout** [comment]
@alissapajer Your simpler case _should_ have a join. To get something that isn’t semantically different from the original query, you need to do
```sql
select count(*) as cnt, state from zips group by state
```
The important bit is that all the projections are either reduced or part of the group key.

**Comment by jdegoes** [comment]
On the simpler query: If QScript supported multi-staged evaluation, the `COUNT(*)` could be done first, and then because it's known it's a single value, it could be inlined in the subsequent query, removing the need for a trivial join with a single constant value. Maybe there are other ways to get that.

**Comment by sellout** [comment]
@jdegoes Yeah, and old Mongo also avoids a join in that case by doing a `$group` with `$count($$ROOT)` and `$push($state)`, then `$unwind`ing `state`. Definitely there are different approaches, and I think they could be QScript transformations to achieve those from a particular join pattern.

**Comment by alissapajer** [comment]
@sellout ah yeah, so for your example 
```
select count(*) as cnt, state from zips group by state
```
we actually do not have a join in the qscript! And actually, at least on my current wip branch, I don't see a join in the original example qscript that @Cmdv provided either. And the result in the REPL against spark actually looks correct! Let me spin up the REPL on master to see if this fix is local to my branch or published yet :) 

@Cmdv what quasar version are you running?

**Comment by alissapajer** [comment]
@Cmdv I just tested your example query against latest quasar and there is no join in the qscript. Can you update your quasar to the latest version and try this again? I'm not sure if the query will work against Couchbase, but if it doesn't you should get a different error.

**Comment by alissapajer** [comment]
@Cmdv ok I just confirmed that this query should be returning correct results against Couchbase.

**Comment by zeeiyerWork** [comment]
@Cmdv -> can this be closed?

**Comment by Cmdv** [comment]
@zeeiyerWork will test out tomorrow morning, I pretty sure I did and the tests still failed but will double check 😄

**Comment by Cmdv** [comment]
unfortunately just ran the above tests against quasar v20.13.7 and I still get the same error. Maybe someone would like to pair to try trouble shout what is happening? 😄
