### ISSUE TITLE
Allow secondary reads on a MongoDB mount

### ISSUE THREAD

**Issue by dugdun** [precog/quasar#2416]
While testing out MongoDB in the 4.2.3 release, I set up a secure MongoDB replica set (three nodes). I put all three servers in the mount section, and then I added the key/value combination of `readPreference`/`secondary` on this mount. I ran several SlamData workspaces, and in looking at the results from `mongostat` it appeared that all reads were still going to the primary instance. I shut down two of the three instances in the replica set, forcing the final member to be a secondary instance, and then got a time out error as follows:

```
Couldn't load this SlamData workspace.
Physical filesystem error.: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=REPLICA_SET, servers=[{address=douglass-mbp:50000, type=REPLICA_SET_SECONDARY, roundTripTime=0.7 ms, state=CONNECTED}, {address=douglass-mbp:50001, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}, {address=douglass-mbp:50002, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}].
```

From the error we can see that SlamData knows that the remaining node is a secondary instance, but it's still trying to connect to the port that the primary was last reported being on. This leads me to believe that we are forcing all reads to be to the primary and we're not honoring the value in the `readPreference` that we pass in the settings.

We should allow users to read from the secondary instances if they are OK with having occasionally out of date information due to replication lag.

This came out of testing for getting documentation written up for different MongoDB configurations in Quasar #2395. Until I can verify that secondary reads are indeed working, I can't do the proper testing and documentation for that issue.

**Comment by damonLL** [comment]
@dugdun - I just tested this and it works for me. I think you may be running into an issue where you're referencing an *existing* workspace from the new mount point.  Any reference to the old mount point (in queries, open cards, etc) will still reference the old mount point, which also means the old connection information (non-secondaries, etc)

I also had to restart SlamData once I setup this mount for it to properly work. It takes about 30 seconds after you click "Mount" for it to actually mount, then I restart SlamData, and I'm verifying that my secondary is being hit by running `mongostat --port=xyz` and pointing it to the secondary. I see that being hit far more than the primary.

Hope this helps.

**Comment by dugdun** [comment]
If you only put in a secondary member as @damonLL did when testing, then yes all reads will go to the secondary member as that is all that SlamData seems to know about. In this type of set up, you will get errors if SlamData needs to try to write data to the MongoDB database as the node it knows about is not a primary member, and it doesn't appear that SlamData is not getting information about the primary node from the MongoDB driver, or is just not using that information and trying to make a connection to the primary.

Here is an error that I got while SlamData was connected only to a secondary member (only this member was listed in the mount dialog) and trying to delete some data in SlamData:

<img width="858" alt="screen shot 2017-08-07 at 08 35 33" src="https://user-images.githubusercontent.com/828514/29031563-ed2ee0b2-7b4b-11e7-848b-3cb2f60ef08c.png">

As you can see, SlamData correctly identifies this node as a secondary member, but it appears that it doesn't try to figure out the primary node. The MongoDB driver will have this information as it keeps track of the different replica set members.

A similar error occurred when I was trying to run a workspace that needed to write temporary data to the MongoDB database while running a workspace.

The situation that @damonLL brings up in his most recent comment about the reads being `getmore`s instead of `query`s is when you add all members of the replica set into the mount dialog and adding the extra key/value parameter of `readPreference / secondary`.  In this case, all the reads are still going to the primary node. While you can see the operations that the node has completed by watching the results of the `mongostat` command line, it's better to run the following query inside of a `mongo` shell:

```
db.serverStatus().opcounters
```

This will show the counts of all operation types processed on a give server. Run the command before and after you run your SlamData workspace.

**Comment by damonLL** [comment]
Thus saith the Mongo Master!!
