### ISSUE TITLE
Maximize index usage for predicates containing conjunctions

### ISSUE THREAD

**Issue by wemrysi** [precog/quasar#2426]
When a QScript filter predicate contains a top-level conjunction, use indexed queries for as many of the predicates as possible, pushing the rest to a post-filter of the indexed search.

**Comment by sellout** [comment]
The new Mongo branch has a `MapFuncCore.flattenAnd` function that is `FreeMap => NonEmptyList[FreeMap]`, which should help with this and #2425.
