### ISSUE TITLE
discovery: Passthrough end-user specified queries in the native-store access-API instead of always requiring the SQL-2->Store-API translation.

### ISSUE THREAD

**Issue by zeeiyerWork** [precog/quasar#2452]
1. Typically the journey of an inbound query journey starts with SQL-2 and ends with NoSQL store's Access API.

2. SQL-2 proffers great benefits to especially those end-users who are not well-versed with the Mount Point's target store Access API and definitely could become in the long-term the "lingua franca of analytics" in an enterprise that heavily adopts Slamdata.

3. However point #2 also implies having to learn SQL-2, which is an additional step for novices to it. The question then becomes whether Slamdata will pass through a query from an end-user if articulated in the target store Access API. 

4. The capability articulated in point #3 has several advantages:
- In case of pathological queries, the power of SQL-2 expression becomes readily visible to end-users.
- It allows Slamdata to co-exist with the ecosystem (and hence improve adoption) so that vendors and end-users that favor something else (e.g. N1QL/SQL++ in case of Couchbase,  XQuery in case of Marklogic, Mongo access apis) over SQL-2 can continue to work with Slamdata, without having to learn SQL-2 first.

Perhaps end-users can just annotate such queries with a "<passThrough>" tag, which when relayed to Quasar, skips the typical steps of SQL-parsing, LP, Qscript etc. and instead simply executes end-user specified query as is and engages Quasar Mostly in terms of the return-journey of results back to the Slamdata App.

**Comment by sellout** [comment]
I think this sounds cool, but it’s actually pretty complicated.

E.g., in Mongo, we serialize out our `WorkflowTask` in a way that should be able to be copy/pasted into a JS file that queries Mongo. But we don’t actually submit that text to Mongo. We use the Java driver, which means we make calls that look like Java calls which 1. don’t look like something a user would want to type and 2. learning that driver API is harder than learning SQL². If we wanted to let a user write things in the “usual” JS Mongo way, we’d need to be able to at least parse all of that into `WorkflowTask`.

I’m not sure how hard it would be in other connectors. In Couchbase we do currently build N1QL strings, and I guess that even if we move away from that, we still _could_ pass literal NIQL strings if provided by a user. In Marklogic, it’s XQuery, but I don’t doubt that there’s already a good parser to give us what we want there.

So, maybe worth trying this on Couchbase first.

Also, this should really just be another node in SQL². Something like
```sql
select city from (native("""db.zips.find({ "pop": { "$gt": 10000 } })""")) as zips
```
and as with other SQL² nodes, it’s a valid query on its own:
```
native("""db.zips.find({ "pop": { "$gt": 10000 } })""")
```

**Comment by beckyconning** [comment]
There are security concerns regarding quasar-advanced and this issue.

Currently permissions are managed via the filesystem. If we go don't parse and evaluate the queries ourselves but rather pass them onto something else then we will not determine which files have been used and whether permission should be granted to the current user. This could allow users to bypass permissions.

Instead perhaps we only provide passthrough usage to the admin group or a passthrough group or something.

**Comment by zeeiyerWork** [comment]
Since QScript is where we branch off from - so the question is does it make sense to parse back from native "query" to QScript and then re-generate the query. Pretty speculative as of now. But leaving this open for 1 more discussion.
