### ISSUE TITLE
discovery: Full-Text-Search as a first class citizen in SQL-2

### ISSUE THREAD

**Issue by zeeiyerWork** [precog/quasar#2454]
Today via SQL-2 one is limited to LIKE. ....

This leads to verbose articulations e.g. to find if a tuple that contains text "foo", one might need to union across col1 LIKE "%foo%" , col2 LIKE "%foo%", ....,\colN LIKE....(I believe this is how the current search card works and we state so in the documentation ->  "Values not preceded by a field name and colon, such as fieldName:, will cause the data source to search through all fields and may cause a delay in producing results from large tables or collections". Further, LIKE has additional limitations vis-a-vis full text search (which offers stemming, synonyms, polysemy etc.)

Providing only the Least common denominator via SQL-2 is a way for us to proceed, but then it does mean leaving some strong capabilities offered by a subset of the target NoSQL store checked out at the door. No easy way around this. One way might be to make a capability available via SQL-2, if the majority of the connectors support it with the ones in the minority throwing a "not supported" exception.  

In this case however, I believe most of our supported stores do support search.

Marklogic:
 cts:query(
  <cts:word-query xmlns:cts="http://marklogic.com/cts">
    <cts:text>word</cts:text>
  </cts:word-query>
)

Couchbase:
[Full Text Search](https://developer.couchbase.com/documentation/server/current/fts/fts-query-types.html#topic_jfq_fn4_1v__query-string-query-syntax)

Mongo:
[Mongo Text Index](https://docs.mongodb.com/manual/core/index-text/)

Spark:
via partnerships with Solr, Elastic Search and various other branded efforts.

**Comment by zeeiyerWork** [comment]
Need comments from @jdegoes (product) on his thoughts about the issue and the prioritization. Hence have moved it to this milestone. It will definitely help in a sliver of use cases, imho. If product is in agreement, we can schedule for 4.4 or 4.5 with some additional specification.

**Comment by jdegoes** [comment]
We definitely need to do this at some point, but we're going to defer this for now, until we have a demonstrated customer requirement.

A full-text query language has to be designed (or perhaps we can just use SlamSearch), and then a parser and ADT have to be developed for the full-text query language, and then each connector will need its own mini-compiler from the ADT to whatever full-text query language it supports. Finally, the issue of how to score matches is somewhat open but can be specified on some backends (e.g. Lucene, ElasticSearch), and that needs thinking through from the perspective of providing a uniform interface with graceful degradation for backends that don't support such a notion.

**Comment by djspiewak** [comment]
Doing the full enchilada (what @jdegoes described) is certainly quite hard, but we can do better than what we have *now* relatively easily.  We could add a straightforward derived function which does a text search on its input, where the thing it is searching for is constrained to be a simple string (i.e. keyword search without any syntax).  This could be implemented as a derived function initially by delegating to `LIKE`, but connectors which have full text search would be able to override this implementation and provide a considerably more optimized version.  This would be a very easy task.
