### ISSUE TITLE
CB: Simple `meta` function usage produces null

### ISSUE THREAD

**Issue by drostron** [precog/quasar#2457]
e.g.
```sql
select meta(*).id from `/cb/testDb/zips`
```
Instead of producing the associated CB document ids as done so in the past, nulls are now returned.

**Comment by sellout** [comment]
Granted, `meta(*).id` (and Mongo’s `_id`, etc.) is a hack until we can easily write queries that avoid the `LeftShift` implied by `from`, but in the mean time, we should perhaps have connector-specific regression tests that make sure _some_ id access works.
