### ISSUE TITLE
Support variable interpolation in non-expression positions

### ISSUE THREAD

**Issue by natefaubion** [precog/quasar#2480]
For reference: https://github.com/slamdata/slamdata/issues/1871

We need the ability to defer `ORDER BY` options to the invocation of a module function, so the viewer of a deck can choose which way to sort the results. I was able to do this fine with `WHERE` clauses because it takes an expression, and thus supports interpolation, but this isn't the case with many other syntactic constructs like projections, group-by, or order-by.

**Comment by zeeiyerWork** [comment]
Awful workaround exists (giant case statement)...But ideal is templating.

**Comment by jdegoes** [comment]
In SQL<sup>2</sup>, everything is an expression, except the individual components of a `SELECT ... FROM ...` clause. Even `ORDER BY` is an expression. 

So most likely this is just an existing limitation of the parser that needs to be overcome.

**Comment by natefaubion** [comment]
@jdegoes The components of the ORDER BY are expressions so I can do something like `ORDER BY :foo ASC, :bar DESC`, but the sorting keywords are not, nor is ORDER BY as a whole.

**Comment by jdegoes** [comment]
`ORDER BY` just compiles to `SORT`, and at one point, you could feed strings in ("Ascending"/"Descending", for example). Not sure if that's still true, though.
