### ISSUE TITLE
Cool idea: Forking file copies in Mimir VFS

### ISSUE THREAD

**Issue by djspiewak** [precog/quasar#2489]
Just to document this…

It is theoretically possible to implement file copying in Mimir's VFS similar to how it is done in modern disk filesystems such as ZFS, BTRFS and APFS: namely, by snapshotting with forked derivation logs.  This works very nicely with Mimir's append-only model and underlying version log.

At the present time, all files in the mimir VFS are run at the HEAD version of their underlying blob.  This versioning is managed by the underlying `VersionLog` which represents a linear, unbroken line of derivations.  This mechanism could be extended relatively simply to allow "free" copies.  Rather than `VersionLog` managing the head metadata, we would simply allow `FreeVFS` to determine which version is considered the head of a particular file, with different versions being the heads of different files.  This complicates `FreeVFS` a bit, and also has an effect on `VFSColumnarTableModule` (where some blob-related metadata has to be tracked), but generally shouldn't be too big of a deal.

With this feature implemented, "copy" gets implemented exactly the same as "link", except that each file would have an independent version (in fact, link might just end up being copy, since we don't need true linking semantics).  Once this is done, copies can change independently.  If copies are unchanged, then data is simply shared indefinitely.

**Comment by djspiewak** [comment]
This is extremely relevant now that file copy is part of the algebra and workspaces are to be stored in mimir.

**Comment by jdegoes** [comment]
Let's chat this week. 👍
