### ISSUE TITLE
epic: Connector: New Mongo - Initial Production Rollout

### ISSUE THREAD

**Issue by alissapajer** [precog/quasar#2500]
This epic tracks all the issues that are required in order for qscript-based mongo (i.e. "new mongo") to go into production. The business deadline for this epic is August 31, 2017.

Issues in this epic may be tagged with various topics (e.g. QScipt, LogicalPlan, MongoDB, SQL, etc.). The common theme among all issues is that they are each required in order for new mongo to go into production. 

If you know of any issues that are required for new mongo that are not in this epic, feel free to add them.

We will track our progress and if we find that we need more resources in order to meet the end-of-August deadline, we can request them from @zeeiyerWork.

**Comment by alissapajer** [comment]
Furthermore there is a label "status: Fixed in New Mongo". This label is added to any issue that is fixed in the new mongo branch. Historically we have been tracking these issues with the "status: On hold" label, but since issues can be "On hold" for other reasons, that label is ambiguous, and so we have a new label.

After new mongo lands in master, we will be able to delete the "Fixed in New Mongo" label so as not to clutter our labels.

**Comment by wemrysi** [comment]
@alissapajer Thank you for organizing this!
