### ISSUE TITLE
Solve for scenario where no Write Access is available to Target store in Mount Point Configuration,

### ISSUE THREAD

**Issue by zeeiyerWork** [precog/quasar#2508]
There have been several conversations in various threads/issues, about  ** Not polluting customer databases with SD artifacts or solving for the scenario where no write-access is available to  target stores specified in Mount Points.**

This issue tries to **summarize the net outcome** of those conversations and is an attempt to arrive at consensus with regards to **specific Next Steps**, to solve the issue satisfactorily.

When one looks at all content that slamD is writes, holistically, it breaks down as:
## **Config** 
1. See [_**here**_](https://github.com/slamdata/slamdata/issues/1997) for next steps.

## **Slamdata artifacts** 
1. There is a nod to this as specified in the Admin Screen, specified as "slamdata artifacts location"
 [here](https://github.com/slamdata/slamdata/issues/1949)). 
![image](https://user-images.githubusercontent.com/24783629/28394112-909305c8-6c9f-11e7-971b-c9aaf9cb41f3.png)
2. The question is whether this location needs to support Connector Algebra or whether just a KV store. 
3. There seems to be differences of opinion between product (@jdegoes please chime in) and engineering. Engineering (@drostron is point) posits that these artifacts do not need typical query algebra and **hence a KV store (Metastore) suffices**. If so, it helps with minimizing TCO (TOTAL Cost of Ownership) of the Slamdata solution, since just 1 Postgres/H2 instance suffices, whereas otherwise another "connector supported" store is needed as well, in addition to Metastore (Postgres).
4. Once agreement, we can proceed with a specific 

## **Slamdata Caches** (materialization of hitherto un-materialized views)
- Short term: No solve
- Medium term (post 4.3 timeline): Write to Mimir (and treat decks with cache cards as possibly needing federation across Mimir and target store specified in mount point). @djspiewak/@alissapajer to decorate with additional comments.

## **Intentional Writes:** (rename, delete, create, copy)
- One POV from most implementors of Quasar = stay "true" to analytics goals.
- Staying "true" would mean only implementing query/read algebra.
- It would mean absolving the "typical" connector of write algebra. 
- Where "typical" = non-Mimir connectors. Mimir is a special purpose connector implementation that supports full fledged write/read.

## Benefits of "write" absolution for typical connectors
- Time-to-market for a given connector, given fewer interfaces to implement.
- Simplification of the code base (One estimate puts the reduction in code for Marklogic connector to be north of 50%), given not only fewer interfaces to implement, but more importantly in terms of not having to deal with complex encoding/decoding of data written by Slamdata to a given store. @estewei please decorate with specific examples.
- Need commentary from @jdegoes (product)/@damonLL (field), before taking next steps, since there are opposing requirements such as[ this one].(https://github.com/slamdata/slamdata/issues/1796).

**Comment by drostron** [comment]
Regarding SlamData artifacts and the future direction for their storage, a few relevant comments are at slamdata/slamdata#1764.

**Comment by jdegoes** [comment]
This is not a priority right now. We can review in Q4 and see if it changes.

**Comment by zeeiyerWork** [comment]
Yes the overall ticket as described in the description is not a priority for 4.3 (maybe for 4.4).

But Admin UI is being worked on now.  So the section on whether slamdata artifacts go to Metastore or not - a response is needed now. If slamdata artifacts can be written to Metastore (as @drostron asserts), there is no need to define a separate artifacts db in the Admin UI mockup.

Similarly direction for "intentional writes" impacts the clarifications from product provided [here](https://github.com/slamdata/slamdata/issues/1796)

**Comment by djspiewak** [comment]
@jdegoes It's worth noting that some of the work described in the OP is *very* low-hanging fruit and addresses real customer confusion.  Notably, the "slamdata artifacts are showing up in my database" problem.  We could move slamdata artifacts to the metastore relatively easily.  This would produce a considerable customer-facing win with very little effort.  It would also produce a considerable internal win, as most of the connectors would be able to rip out quite a bit of code that currently has to work around the "arbitrary read/write VFS" nature of being a backend.  Again, while I understand it's not a priority, it's relatively low cost for the win on two fronts.

Allowing strictly read-only mounts is something that would have to wait until we solve the caching problem, and that's certainly non-trivial.  I don't think anyone was realistically expecting that issue could get resolved before Q1 next year.

**Comment by jdegoes** [comment]
@djspiewak 

I'm not sure it's low-hanging fruit. It's a complex issue:

1. No matter what, we would have to preserve data import, because it's used internally and by customers and is necessary for tools like ours that have no federation (no other way to incorporate reference data into a computation). This means write and delete ability, at minimum (delete to undo writes and avoid filling up data stores with irrelevant junk and avoid forcing users to contact IT to undo mistakes). You could potentially delete MOVE and COPY, which means there's still a lot of read/write code, especially since move and copy can be implemented (poorly) in terms of read/write/delete.
2. If we force all decks to be written to metadata, then they become huge JSON blobs stored as `VARCHAR` in single columns in H2 and maybe JSON in Postgres, which is not a great solution and has no clear path to a future multi-user architecture because of the poor or non-existent support for indexing, atomic operations, and so forth. Ideally the front-end would be re-engineered to use relational data, with proper schema migration, and so forth, which would permit an efficient solution, but take a long time to engineer and test.
3. If all decks are only ever written to metadata, then we need to write migration code for all current users that can take existing decks and read them from the file system and then transport them to the metadata layer. This code has to be written, extremely well tested, support all prior 4.x versions of SlamData, and then supported in the future because users use old versions of SlamData.

All of this is valuable refactoring work, but at this point, we have gigantic priorities that are not being addressed and will be delayed if we devote time to cleaning up the code base with a better data access layer.

**Comment by wemrysi** [comment]
@jdegoes Would you mind clarifying which of these current capabilities are actually features and which are incidental/implementation artifacts (if any), namely:

1. Is it a feature to be able to upload arbitrary data conforming to the Quasar data model into Quasar and be able to explore and perform analytics on it?

2. Is it a feature to be able to upload arbitrary data conforming to the Quasar data model into a supported data store and be able to explore and perform analytics on it?

(1) seems like a useful feature, especially for the single-user desktop use-case, but I find (2) less compelling from an ROI standpoint. We currently implement (1) via (2), however it would seem this doesn't necessarily have to be the case. We could still support (1) via `mimir` and relieve the other data stores of the burden of  a) supporting a general purpose VFS interface and b) full-fidelity querying of arbitrary data.

As @jedesah and @djspiewak [have](https://github.com/slamdata/slamdata/issues/1796#issuecomment-316604125) [mentioned](https://github.com/quasar-analytics/quasar/issues/2508#issuecomment-316759444), supporting a) and b) can involve considerable effort, depending on the data store, and significant implications on what it means to be a connector. The ability to ingest arbitrary, typed, data and expect both the structure and types to be preserved without explicit casting when referenced in a query implies a lot of embedding and runtime detection of that embedding during queries for many connectors. And the investment made to support this functionality goes unrealized for most (all?) user-created data ingested into a data store outside of Quasar.

I agree that eliminating (2) is a complex issue and I haven't mentioned (nor have I fully considered) all the ways it would affect the system, but I think discussing the distinction would be useful from an architecture standpoint, going forward.

**Comment by jdegoes** [comment]
Both (1) and (2) are considered features and currently used by customers. (2) can be removed as soon as we can do federated queries and don't rely on each connector to do 100% of the computation (until then, there's no way to, e.g., take a reference data set and incorporate it into a query with the database, which I have seen customers do). (1) will likely always be important for Mimir / desktop / "Tableau for NoSQL", but is probably not important long-term for the individual connectors.

I understand it adds significant work, but there's really no way around it that doesn't involve both (a) lots of refactoring, and (b) loss of features that customers use.

**Comment by zeeiyerWork** [comment]
1. I think the term "Slamdata Artifacts" means different things to different people and merits more clarification. It means 
- A> Workspaces (which are JSONs).
- B> It means temporary data created during query computation (such as joins, multi-stage map-reduce etc.)

2. <B> is similar to serverside cache (Third sub-header in the description) and cannot be solved now. The one hope in 4.4. or later is to be able to write to Mimir and then execute federated queries against Mimir and target-store-with-no-write-access.

3. Wrt <A>
- These could go into Postgres (without being written as `varchar` [Postgres does support a JSON column type, although limited](https://www.postgresql.org/docs/9.6/static/datatype-json.html). 
- But the point is taken that it can't just be a KV store which treats the Json as a blob. It needs to be more, since even though TODAY the only front-end request is "give me the JSON" for this key, TOMORROW we may want something richer (e.g. show me all decks that have this card - i.e. snippet of JSON, multi-user and what not). 
- So, for 4.3 (and the conceivable future) we will simply write it into a store that supports Connector Algebra - although as per the picture [in this issue](https://github.com/slamdata/slamdata/issues/1631), it does introduce an additional potential point of failure and increases total cost of ownership (TCO) of the solution.

- Executing <3>, spec'ed in Admin UI earlier is in scope for 4.3 and will require the backed to interpret what a workspace is and divert it to the configured "slamdata-artifacts-db". @jr (and Christoph) are in agreement. It is a STEP in the direction of solving the overall issue in this ticket (which will need treatment for Data-imported into 3-PStore/Quasar, Server-side Cache and Temporary data connectors create to handle Map-Reduce/Joins). This latter part is not in scope but needs to be considered now by @djspiewak/@alissapajer (Mimir team), so we can execute more easily when the time comes.

If there is agreement, it would mean we are in consensus (and I believe we are in based on John's comment and opinions articulated in meetings with relevant backend engineers).
