### ISSUE TITLE
Reduction on a shifted set produces incorrectly bucketed QScript.

### ISSUE THREAD

**Issue by alissapajer** [precog/quasar#2515]
```sql
select count(loc[*]) from zips
```
This reduction should be bucketing on the row level ids of `zips`, but instead it's requesting a single bucket. The left shift should put the array indices onto the identities stack. Then we pop those off and bucket on the remaining stack. Instead, `QScript` is incorrectly requesting a single bucket `Constant(Null())`. 
```
Reduce
├─ LeftShift
│  ├─ ShiftedRead(/home/apolune/spark_local_test/zips, ExcludeId)
│  ├─ Struct
│  │  ╰─ Guard
│  │     ├─ ○
│  │     ├─ Type(Obj(Map[], Some(Top)))
│  │     ├─ Guard
│  │     │  ├─ ProjectField
│  │     │  │  ├─ ○
│  │     │  │  ╰─ Constant(Str(loc))
│  │     │  ├─ Type(FlexArr(0, None, Top))
│  │     │  ├─ ProjectField
│  │     │  │  ├─ ○
│  │     │  │  ╰─ Constant(Str(loc))
│  │     │  ╰─ Undefined
│  │     ╰─ Undefined
│  ├─ IdStatus
│  │  ╰─ IdStatus(ExcludeId)
│  ╰─ Repair
│     ╰─ RightSide
├─ Bucket
│  ╰─ Constant(Null())
├─ Reducers
│  ╰─ Count
│     ╰─ ○
╰─ Repair
   ╰─ ReduceIndex(Some(0))
```
The above `QScript` produces an incorrect result of
```
 value  |
--------|
  58706 |
```
Instead we expect one result per row of the original dataset where each value is `2` (the size of each array `zips.loc`). Or phrased differently, the results are the counts of the number of rows per row level identity, after we flatten.

For a second example, if we consider
```sql
select sum(loc[*]) from zips
```
then we'd expect one result per row of the original dataset where that result is the sum of the values in each array.

**Comment by jdegoes** [comment]
The query `select count(loc[*]) from zips` will yield `2 * count(zips)`, assuming every `loc` contains two entries and every row contains a `loc`.

The query `select count(loc[_]) from zips` should yield `count(zips)` results, where every entry is a 2 (the length of each array), under the preceding assumptions.

**Comment by alissapajer** [comment]
Oh, looks like I confused `[*]` (flatten array) with `[_]` (shift array). In my original post, my intention was to flatten the arrays, putting the array indices at the head of the identity vector. But that is actually what `loc[_]` does, not `loc[*]`. I just verified the qscript for the `loc[_]` version of the query and it is correct (and is returning correct results in spark). Yay!

@jdegoes to make sure we're on the same page, in order to achieve the results you are expecting for the `[*]` version of the query, we'd need to be putting 2 pieces of information into the identity vector when we do the flatten, so that when we pop one off in order to do the reduction, each row has unique identities (i.e. each row will be its own bucket). Or alternatively we could be modifying the identities to achieve this some other way? If `[*]` flattens the array _without_ affecting the provenance, then I'd argue that `select count(loc[*]) from zips` should instead return a single result because there would just be one piece of information in the identity vector after we perform the flatten, we'd pop that piece off, and then we'd reduce on a single bucket.

**Comment by jdegoes** [comment]
@alissapajer If you look at the specs, both track provenance, but only `[_]` adds a new dimension; the flattening operator merely tacks on more information to the end of the last dimension.

This is a difference between present QScript and the MRA spec. In MRA, `foo[*].bar + foo[*].baz` does a pairwise addition on array elements, and of course flattens the result, whereas I believe in QScript, it results in a cross—which is incorrect if true.

**Comment by alissapajer** [comment]
@jdegoes oh, yeah, I should have just looked at the spec :) we're all clear on that front, thanks! QScript is indeed handling `[*]` differently than what MRA prescribes.

**Comment by alissapajer** [comment]
Following up, QScript is actually returning the correct result for all the queries mentioned in this issue, including `foo[*].bar + foo[*].baz` and `select count(loc[*]) from zips`. I'm going to add some tests to make sure we maintain this behavior and will close the issue when those tests land.

**Comment by jdegoes** [comment]
@alissapajer So `foo[*].bar + foo[*].baz` returns an element-wise addition?

**Comment by alissapajer** [comment]
@jdegoes here is an example run on master against spark. Please confirm this is doing what you expect.

```
💪 $ select foo[*].bar * foo[*].baz from flattentest

 value |
-------|
    35 |
     6 |
   143 |
     6 |
   323 |
     6 |
```
And the data `flattentest`:
```
{"foo": [{"bar": 5,  "baz": 7},  {"bar": 3, "baz": 2}]}
{"foo": [{"bar": 11, "baz": 13}, {"bar": 3, "baz": 2}]}
{"foo": [{"bar": 17, "baz": 19}, {"bar": 3, "baz": 2}]}
```
An example identity vector for both `foo[*].bar` and `foo[*].baz` is `["flattentest", _id1 -> 0]` with the two respectively corresponding values `5` and `7`.

**Comment by jdegoes** [comment]
The result set looks correct to me. 👍

**Comment by alissapajer** [comment]
@jdegoes awesome. Glad you, me, and `QScript` are all on the same page :)

**Comment by alissapajer** [comment]
Keeping this issue open until we add integration tests for:
```sql
select count(loc[*]) from zips
```
```sql
select count(loc[_]) from zips
```
```sql
select foo[*].bar * foo[*].baz from flattentest
```
```sql
select foo[_].bar * foo[_].baz from flattentest
```

**Comment by alissapajer** [comment]
Hm, so what isn't working correctly is this query:
```sql
select foo[_].bar * foo[*].baz from flattentest
```
An example identity vector for the shift looks like `["flattentest", _id1, 0]` and an identity vector for the flatten looks like `["flattentest", _id1 -> 0]`. So the two sides should autojoin only as far as `"flattentest"`, meaning we get a full cross across all rows after shifting/flattening. But alas the results in spark are the same as the version with `foo[*].bar * foo[*].baz`. This is a bug in `QScript`.

**Comment by jdegoes** [comment]
Actually, they will auto-join as far as `_id` (auto-join goes depth-wise, as well as length-wise).

**Comment by alissapajer** [comment]
Got it, so we'd expect a full cross within each row that shares an `_id`. So the results of `select foo[_].bar * foo[*].baz from flattentest` should have size 12.

**Comment by zeeiyerWork** [comment]
Moving this to a later iteration since it no longer has the "initial production rollout" label, given the preceding commentary from August.
