### ISSUE TITLE
Querying a database or directory on mongodb fails even in next-major

### ISSUE THREAD

**Issue by beckyconning** [precog/quasar#2563]

**Comment by beckyconning** [comment]
It does work on Marklogic however it does not seem to work on Quasar.

**Comment by wemrysi** [comment]
Currently, querying a toplevel directory that references a database, like `select * from /mongo32/testdata` results in

`Quasar error: File /mongo32/testdata is invalid: path names a database, but no collection`

and querying a directory further down like `select * from /mongo32/testdata/null` results in

`Quasar error: File not found: /mongo32/testdata/null`

**Comment by zeeiyerWork** [comment]
@rintcius -> can you please investigate.

**Comment by rintcius** [comment]
@zeeiyerWork  Looks like this functionality is not implemented indeed. Let me know the priority relative to #2502 and I will pick up accordingly after mongo driver upgrade has been finished.

**Comment by zeeiyerWork** [comment]
@jsantos17 -> Please take a look as @rintcius wraps up other issues/
