### ISSUE TITLE
MapFuncCore's Range Operation is Ill-Defined

### ISSUE THREAD

**Issue by djspiewak** [precog/quasar#2625]
`Range` is defined to return multiple rows per invocation.  For example:

```
Range(0, 3)
```

id | value
--- | ----
0 | 0
1 | 1
2 | 2

This is sort of bonkers, since it allows completely non-sensical things such as joining where the key contains a `Range` (which is an operation that has no sane definition).

The correct definition of `Range` would be to return an *array* in a single row, which the user can subsequently flatten:

```
Range(0, 3)
```

id | value
--- | ----
0 | [0, 1, 2]

This would be implementable by all connectors, and has a sane interpretation in all cases of `MapFunc`.

As a general rule, `MapFunc`s should *never* operate on anything more than a single row.  A single row may be *eliminated* (by going to `Undefined`), or it may be transformed in a perhaps-structural fashion, but you cannot return multiple rows, and you cannot operate on more than one row at a time.  Any functions which violate this invariant should not be included in `MapFunc`, since their inclusion prevents sane interpretation of joins, sorts, and other row-level operations.

If we cannot redefine `Range` in the fashion I describe (for example, if this operation is part of ANSII SQL and constrained to behave in a multi-row fashion), then we need to remove it from `MapFunc`.

**Comment by jdegoes** [comment]
💯 The current definition is broken and doesn't mean anything sensible.
