### ISSUE TITLE
Rework ReadFile/QueryFile To Avoid Boxing

### ISSUE THREAD

**Issue by djspiewak** [precog/quasar#2626]
Currently, the `More`/`Read` cases in these algebrae produce `Vector[Data]`, which requires hard-boxing into `Data` and ultimately indirection around what the final output format may be (for example, CSV).  A better approach would be to push down the rendering of data to the backend by rephrasing the whole algebra.  This is most easily seen with `ReadFile`, though `QueryFile` is analogous.

My proposed cases are the following:

```scala
sealed abstract class ReadFile[A]

object ReadFile {

  final case class Open(
      file: AFile,
      offset: Natural,
      limit: Option[Positive],
      mimeType: MimeType) extends ReadFile[FileSystemError \/ ReadHandle]

  final case class Read(h: ReadHandle)
      extends ReadFile[FileSystemError \/ Option[CharBuffer]]

  final case class Close(h: ReadHandle)
      extends ReadFile[Unit]
}
```

Where `MimeType` is something like the following:

```scala
sealed abstract class MimeType(override val toString: String) extends Product with Serializable

object MimeType {
  case object JSON extends MimeType("application/json")
  case object CSV extends MimeType("text/csv")
}
```

Give or take.

Heads up, @jdegoes

**Comment by jdegoes** [comment]
👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍

**Comment by zeeiyerWork** [comment]
@djspiewak -> Wrt your prior query on Slack, this is the ticket that @natefaubion created which also references to problems he is having which he attributes to the values being boxed (see comments). Seems like we should leave these as separate issues.

**Comment by djspiewak** [comment]
@zeeiyerWork Did you attempt to link a ticket?  I created this ticket, as well as the only other ticket linked to this one.

**Comment by zeeiyerWork** [comment]
yep -> #2592

**Comment by natefaubion** [comment]
I don't know if that issue has anything to do with value boxing specifically. For all I know, it could be fixed, but I couldn't run my test case due to that failure. I worked around the value boxing (still old mongo) another way.

**Comment by djspiewak** [comment]
Yeah I don't think this is related to Nate's issue.
