### ISSUE TITLE
Mimir directory contains broken HEAD symbolic link

### ISSUE THREAD

**Issue by damonLL** [precog/quasar#2629]
@djspiewak asked that I create this issue. Noticed after extracting the default data set for Mimir that for each dataset directory (physical file system directory) there is a file named `HEAD` that is a broken symbolic link pointing to a `/tmp` path.

**Comment by djspiewak** [comment]
Basically, `HEAD` is being created as an absolute symlink, rather than relative to the current directory (which would make a lot more sense).  It doesn't affect functionality, since mimir ignores the `HEAD` links, but it should be rectified.
