### ISSUE TITLE
TYPE_OF returns unexpected values from MongoDB

### ISSUE THREAD

**Issue by damonLL** [precog/quasar#2658]
Not sure if this is related to Issue #2200 or not?

Came across this while writing up Doc Issue [#56](https://github.com/slamdata/slamdata-docs/issues/56)

I have inserted two documents into MongoDB:

```
rs:PRIMARY> db.types.insert({field1:"NumberInt", field2:NumberInt(88602117)})
WriteResult({ "nInserted" : 1 })
rs:PRIMARY> db.types.insert({field1:"NumberLong", field2:NumberLong(3921412)})
WriteResult({ "nInserted" : 1 })
```
`field1` is simply a description of the value in `field2`. You can see that I prefixed the actual value of `field2` with the data type I wanted.

From Mongo shell `find` I see:
```
rs:PRIMARY> db.types.find().pretty()
{
	"_id" : ObjectId("599ae89c687df0cda73d475f"),
	"field1" : "NumberInt",
	"field2" : 88602117
}
{
	"_id" : ObjectId("599ae8a7687df0cda73d4760"),
	"field1" : "NumberLong",
	"field2" : NumberLong(3921412)
}
```
It appears that `field2` in the first document, **presumably** of type `NumberInt` within Mongo, is stored simply as a numeric value. The second document's `field2` appears as `NumberLong` which is what I specified.

Both documents, however, show up as type `decimal` when queried from Quasar/SD:

```
💪 $ select field1, field2, type_of(field2) as f2_type from `/mongodb/data/types`
Query time: 0.1s
 field1      | field2      | f2_type  |
-------------|-------------|----------|
 NumberInt   |    88602117 | decimal  |
 NumberLong  |     3921412 | decimal  |
```

And finally:
* For the `NumberInt` document, Mongo `typeof` command says it is of type `number`.
* For the `NumberLong` document, Mongo `typeof` command says it is of type `object`. 

This is strange because the `find()` command above reports it differently.

**Comment by rintcius** [comment]
There's a TODO in the code related to this: 
https://github.com/quasar-analytics/quasar/blob/next-major/mongodb/src/main/scala/quasar/physical/mongodb/expression/ExprOpCore.scala#L395-L396

```
          // TODO: figure out how to distinguish integer
          $cond($lt(a1, $literal(Bson.Text(""))),                  $literal(Bson.Text("decimal")),
```
