### ISSUE TITLE
Fix test expectations/regressions in mongo planner specs

### ISSUE THREAD

**Issue by alissapajer** [precog/quasar#2667]
There are ~80 disabled tests disabled with “Not on par with old (LP-based) connector” in the [mongo planner tests](https://github.com/quasar-analytics/quasar/blob/master/mongodb/src/test/scala/quasar/physical/mongodb/planner.scala).

We need to enable these tests before merging `next-major` into `master`. Some of these test failures may be regressions while others represent only differences between two equivalent and correct plans.

**Comment by alissapajer** [comment]
We only need to enable the tests for mongo 3.2 and higher since quasar isn't supporting any lower versions of mongo anymore.

**Comment by zeeiyerWork** [comment]
Currently 60 instances of pendingUntilFixed(notOnPar) in 
https://github.com/quasar-analytics/quasar/blob/master/mongodb/src/test/scala/quasar/physical/mongodb/planner.scala....

Based on work from @nicflores , @rintcius , @jsantos17 - this should come down. Any guesstimate of what it is expected to come down to post merge of your work?

**Comment by rintcius** [comment]
@zeeiyerWork :  

* @nicflores 's PR solves 3 and simplifies a bunch of others
* #3029 will solve 2, possibly more
* now #3001 is in `master` the first join test will be onPar once the qscript for it is optimal (this is verified in #3028). We need to add similar unit tests for other join tests. After that we know more.
* @jsantos17 's work is currently not focused on these tests, unless I have missed something
