### ISSUE TITLE
Consistent implementation wrt implicit select value semantics

### ISSUE THREAD

**Issue by rintcius** [precog/quasar#2682]
Currently implicit select value semantics is only partly implemented, which leads to confusion. We need to either implement this consistently throughout or revert the part that is implemented.

See #2671 for more info. Needs to be discussed with @jdegoes

**Comment by jdegoes** [comment]
See [here](https://github.com/quasar-analytics/quasar/pull/2671#issuecomment-325144217).

**Comment by rintcius** [comment]
See here for another example of inconsistency: https://github.com/quasar-analytics/quasar/issues/2061#issuecomment-328181658
