### ISSUE TITLE
Support XML

### ISSUE THREAD

**Issue by safareli** [precog/quasar#2760]
Currently you can export/import data in JSON/CSV but not in XML.

**Comment by djspiewak** [comment]
https://github.com/djspiewak/quasar/blob/master/web/src/main/scala/quasar/api/MessageFormat.scala#L90-L243

**Comment by jsantos17** [comment]
We have some code in the Marklogic connector that could potentially make this very easy. Checkout `quasar.physical.marklogic.fs`. We have `encodeXML` and `decodeXML` to/from `Data` in there. Is there a customer request or something for this?

**Comment by djspiewak** [comment]
Effectively yes: https://github.com/slamdata/slamdata/issues/1800

**Comment by jsantos17** [comment]
@djspiewak great. Would be good to do some prioritizing here @zeeiyerWork?

**Comment by zeeiyerWork** [comment]
Well we can start with json/csv and then add XML in 43x.
