### ISSUE TITLE
`$set` in precise-syntax JSON doesn't seem to be supported

### ISSUE THREAD

**Issue by garyb** [precog/quasar#2763]
It'd described in the [readme examples](https://github.com/quasar-analytics/quasar#examples):

``` json
{ "testSet": { "$set": [1, 2, 3] } }
{ "testSet": { "$set": [4, 5] } }
```

Trying to upload this on the mongo connector results in:

``` json
{ "error": { "status": "Physical filesystem error.", "detail": { "message": "Invalid BSON field name $set" } } }
```

Trying to upload it with the spark connector does result in an upload, but it turns the values into a map:

``` json
{ "testSet": { "$obj": { "$set": [ 1, 2, 3 ] } } }
{ "testSet": { "$obj": { "$set": [ 4, 5 ] } } }
```

If you directly place a JSON file with the values in the spark local directory, viewing it results in an empty result set.

edit: I don't think this a priority at all, just an oddity I stumbled across while testing SST stuff.

**Comment by wemrysi** [comment]
@garyb Thanks for the report, I don't think `$set` was ever intended to be supported, it is some of the antiquated internal data model leaking out.

I think the solution here is to remove this from the docs.

**Comment by garyb** [comment]
> I think the solution here is to remove this from the docs.

Yeah, I did wonder if that might be the case!
