### ISSUE TITLE
Mimir crashes indefinitely on write if quasar has no write access to the mimir directory

### ISSUE THREAD

**Issue by beckyconning** [precog/quasar#2766]
After reattempting the following error is raised.

An error occured when counting the preview data.
Physical filesystem error.: Recipient[Actor[akka://nihdbExecutorActorSystem/user/$f#953470464]] had already been terminated. Sender[null] sent the message of type "quasar.niflheim.GetSnapshot$".

Providing write access to the user / group quasar is launched on and restarting quasar resolves this.

It would be nice if this didn't crash mimir and if it threw a specific error saying that it doesn't have write access to its store.

**Comment by djspiewak** [comment]
Doesn't seem difficult to do.  Though given how poor our error propagation is inside backends, it's probably going to be a nightmare.  `RealPOSIX` is where the check needs to be made.
