### ISSUE TITLE
Improve Test Suite

### ISSUE THREAD

**Issue by rintcius** [precog/quasar#2802]
It would be nice if we would extend our Test Suite. Currently the suite verifies the query results for each connector, but I think we can use the same mechanism to also test other key intermediate phase results so that we get more detailed feedback on the impact of our changes. Some things we can start tracking:

* last Logical Plan
* last generic QScript
* connector artefacts (connector specific QScript changes, generated queries, etc. Basically whatever a connector decides to be important to track)

I'd like this to be a lightweight solution, in the sense that it shouldn't require any coding to add new tests and test expectations. We could gradually move tests like https://github.com/quasar-analytics/quasar/blob/master/connector/src/test/scala/quasar/qscript/QScript.scala and https://github.com/quasar-analytics/quasar/blob/master/mongodb/src/test/scala/quasar/physical/mongodb/planner.scala into this suite.

I imagine we'd inverse the dependency of part of the `it` module, so that e.g. LP tests can live in `frontend` and QScript tests can live in `connector` (A lot of these tests don't need to be ITs BTW)
 
We could start by tracking the rendered tree as a String and later add parsers for them. E.g. it'd be cool if we had a `QScript` parser.

**Comment by djspiewak** [comment]
I like the idea of being able to test the phases along the way, but I worry about such tests being really brittle.  Imagine how painful it would be to adjust the generated qscript to be more optimal if doing so also causes every integration test to start failing (even when the functionality is unchanged).

**Comment by rintcius** [comment]
@djspiewak we certainly should not do these things manually. What I have done in the past for tests like this, is to create an update mode, which just writes the actual results into the expectation files.

Even if the changes are too much to review completely, just the fact that we can trace our changes more completely and retroactively would be very useful, I think.
