### ISSUE TITLE
REST endpoint to provide data-set count.

### ISSUE THREAD

**Issue by zeeiyerWork** [precog/quasar#2812]
_From @zeeiyerWork on September 23, 2017 22:37_

The frontend is peppered with calls to first get **count** of a given data-set, before proceeding with "visualization" related or other work. 

If the overhead associated with the count query could be reduced, then it would therefore mean a significant performance benefit for end-users. 

Therefore this proposal is around a custom end-point to get count of a data-set. In case of Mimir, this measure is held in memory so should return instantaneously. In case of other connectors, it would imply a query to the backend, but one would have avoided all the overhead for the count-query around SQL-2-parsing -> LP -> QScript.

cc: @djspiewak, @garyb 

_Copied from original issue: slamdata/slamdata-backend#245_

**Comment by zeeiyerWork** [comment]
_From @garyb on September 25, 2017 13:0_

I think maybe this issue should be on Quasar, as it's not a SlamData-specific feature?

**Comment by zeeiyerWork** [comment]
At some point we should also discuss if some improvements are available just to Slamdata - given the conversation of quasar usage without attribution. And what that means. But yes, for now.

**Comment by djspiewak** [comment]
This isn't something that even *could* be in just SDBE, given the current connector architecture.  So it's not really an option here.
