### ISSUE TITLE
epic: Quasar Doesn't Build/Work on Windows

### ISSUE THREAD

**Issue by djspiewak** [precog/quasar#2814]
A lot of stuff is currently broken when you try to build and use quasar on Windows.  Heck, some things about just *using* quasar on windows are broken.  These should be fixed, and we should have automated builds which ensure that they don't get broken again.

**Comment by zeeiyerWork** [comment]
@djspiewak -> yes this should be fixed, but it is of lower priority. Confirmed with outbound.

**Comment by djspiewak** [comment]
I'm partially just recording things to come back to them later.
