### ISSUE TITLE
Server does not stop when Enter is pressed

### ISSUE THREAD

**Issue by alissapajer** [precog/quasar#2827]
When I run quasar from the command line, for example
```
$ java -jar quasar-web-assembly-24.0.15.jar -c quasar-config.json
```
the last two lines printed are
```
Server started listening on port 8090
Press Enter to stop.
```
If I start the server and then press `Enter` without activating any connector, it will print `Stopped server listening on port 8090` and then return me to the command line prompt as expected.

But if I activate a connector (e.g. navigate through the file system in SlamData or run a query), when I press `Enter` it prints `Stopped server listening on port 8090` and then just hangs, never returning a command line prompt.

**Comment by nicflores** [comment]
It is likely this error is now fixed in PR [#2975](https://github.com/quasar-analytics/quasar/pull/2975).
