### ISSUE TITLE
Refine mongodb planner tests

### ISSUE THREAD

**Issue by rintcius** [precog/quasar#2829]
Pending mongodb tests are tracked now (see #2801) , but they are tracked using a string comparison. This may lead to tests failing too often, in the sense that tests would also fail when the change is insignificant for a particular test case. It would be nice if we can verify only aspects of a workflow that are important for a particular test case.

Note that the reason why string comparison was introduced is that this is more lightweight than having to specify the expectations in code. We should think about a solution that is both easy to maintain and that can filter out insignificant changes.

Also note that filtering out insignificant changes has the downside that this is based on the developer's perception of what is significant and what not. In case a change stays under the radar incorrectly in hindsight, we have no commit history to easily track when exactly something broke. However, a test that checks the _complete_ query instead, may give noise but also associates production code changes directly with changed expectations in the commit history (and being able to generate the new expectations may make the noise less annoying)

**Comment by jsantos17** [comment]
We should re-evaluate if we still need the tracking at the end of October and remove it altogether if it's no longer useful.
