### ISSUE TITLE
unexpected result with 2 left joins

### ISSUE THREAD

**Issue by janfeyen** [precog/quasar#2871]
When I do 2 left joins, I get unexpected results.
given 3 collections
collection picups has _id, UserId and a BusinessId, only one will have a value
collection users has _id and name
collection business has _id and name

```
SELECT
    count(p.vehicleId)
from `/picup/picup/reports/picups` as p
```
returns 238 which is correct

```
SELECT
    count(p.vehicleId)
from `/picup/picup/reports/picups` as p
LEFT OUTER JOIN `/picup/picup/reports/users` as u on p.UserId = u.`_id`
```
returns 238 which is correct
```
SELECT
    count(p.vehicleId)
from `/picup/picup/reports/picups` as p
LEFT OUTER JOIN `/picup/picup/reports/businesses` as b on p.BusinessId = b.`_id`
```
returns 238 which is correct
```
SELECT
    count(p.vehicleId)
from `/picup/picup/reports/picups` as p
LEFT OUTER JOIN `/picup/picup/reports/users` as u on p.UserId = u.`_id`
LEFT OUTER JOIN `/picup/picup/reports/businesses` as b on p.BusinessId = b.`_id`
```
returns 220 which is not what I would expect

we are running quasar analytics v18.7.4

**Comment by djspiewak** [comment]
18.7.4 is quite old.  Have you tried with the latest?  Also, what connector is this?  If mongo, what version?

**Comment by zeeiyerWork** [comment]
Am assuming Mongo - please correct if inaccurate.
