### ISSUE TITLE
Dashboard for status of integration (demo) queries run against quasar

### ISSUE THREAD

**Issue by alissapajer** [precog/quasar#2888]
The idea is to have a dashboard that is populated by travis data, showing the status of each demo query (or otherwise important query) run against each connector. Each time we publish quasar, the dashboard is automatically updated. This tool would allow everyone to easily see the status of all the important queries against all connectors.

**Comment by zeeiyerWork** [comment]
It might be good to generate dashboards via Slamdata as yet another dogfooding example -
like what's been done with Github issues. (This just needs some minor updates and needs to be pushed to the demo server). 

@nicflores -> Can you look into how to export Travis data (see https://docs.travis-ci.com/api) to JSON (am assuming there is no direct way to export into a nosql db). Then we can import JSON arrays into Mongodb and build dashboards using Slamdata like we did with Github issues.

**Comment by nicflores** [comment]
This will depend on how travis gains information about the "status of each demo query ran against each connector". If this data ends up in the log file, then that means extracting the log file from travis using the information in [this](https://docs.travis-ci.com/api#logs) section of the Travis api doc. This means parsing the log and extracting the status of the query against a particular connector.

If the entire test query suite were its own build and each query or group of queries were a job in that build then we could query the build for its job [id's](https://docs.travis-ci.com/api#jobs) and then inspect the build state of each job.
