### ISSUE TITLE
citiesByLargestZip.test failing intermittently

### ISSUE THREAD

**Issue by alissapajer** [precog/quasar#2927]
The following failure occurred in the master build for mongo 3.4.

```
[error] x cities with largest individual zip codes [./citiesByLargestZip.test] (3 seconds, 375 ms)
[error]  ; object[(city,"BELL GARDENS")] does not match object[(city,"CHICAGO")]; object[(city,"JACKSON HEIGHTS")] does not match object[(city,"BROOKLYN")]; object[(city,"ARLETA")] does not match object[(city,"NEW YORK")]; object[(city,"SOUTH GATE")] does not match object[(city,"BELL GARDENS")]; object[(city,"RIDGEWOOD")] does not match object[(city,"LOS ANGELES")] (file:1)
```

This is strange because this test passed the PR build that preceded the master build. And there should be nothing nondeterministic about this test.

EDIT: Seen in the master build for 25.0.9

**Comment by alissapajer** [comment]
I reran the mongo 3.4 job that failed, and it passed. So there is indeed some nondeterminism _somewhere_ in the pipeline. The mongo plans that quasar produces should of course be deterministic, and I haven't previously seen any evidence to the contrary. 

Looking at the query itself
```sql
select distinct city from zips order by pop desc limit 5
```
there actually is nondeterminism baked in. If there are multiple rows for the same `city`, some with different `pop` values, then depending on which `city` we select, a different `pop` value would be associated with it, and so the ordering of the results would change.

I'll look at the results that the query returned above to see if this could account for the failure.

**Comment by djspiewak** [comment]
This definitely isn't a deterministic query (as we've discussed).  I would guess that Mongo isn't being as coincidentally-stable in its sorting and selection as Mimir is, meaning that sometimes you get a different secondary (the unconstrained) sort order and the `limit` sees a different set of five rows.
