### ISSUE TITLE
Mechanism to emit warnings/information during any phase

### ISSUE THREAD

**Issue by alissapajer** [precog/quasar#2938]
All phases of the parser/compiler (SQL^2 parser through qscript) need to be able to emit warnings or other information to the user.

For example, we may want to issue a deprecation warning. Or we might want to warn a user they are running a query that we statically know returns zero results. Or we might want to suggest to a user that they create a certain database index.

This issue is to create the mechanism that will allow for this information to be emitted.

**Comment by wemrysi** [comment]
Maybe we can extend the existing phase results mechanism, expanding the datatype logged to include constructors for warnings and informative messages in addition to compile phases. We could then filter/partition the log based on context (e.g. separating out compile phases as "debug" output, etc).
