### ISSUE TITLE
Query with interval function does not behave properly (on Spark)

### ISSUE THREAD

**Issue by EncodePanda** [precog/quasar#2949]
When creating workspace with following query we get wrong results

```
select
timestamp(loginTimestamp) as ts,
interval("PT7H") as inter, 
timestamp(loginTimestamp) - interval("PT7H") as loginTimestampMST
from
    :auditlog
```

This creates an error. Functions `timestamp` and `interval` behave properly, but `subtract` interval from timestamp fails.

**Comment by rabbitonweb** [comment]
Same observed for mimir
