### ISSUE TITLE
Query with interval function does not behave properly (on new Mongo) 

### ISSUE THREAD

**Issue by EncodePanda** [precog/quasar#2950]
Similar issue as #2949 but different outcome

When creating workspace with following query we get wrong results

```
select
timestamp(loginTimestamp) as ts,
interval("PT7H") as inter, 
timestamp(loginTimestamp) - interval("PT7H") as loginTimestampMST
from
    :auditlog
```

This creates an error. Function `timestamp` works correctly but `interval` returns an `int` instead of an `interval`

**Comment by drostron** [comment]
This depends on #2982
