### ISSUE TITLE
Value wrapping case on mongo 3.4/Quasar 25.0.16

### ISSUE THREAD

**Issue by garyb** [precog/quasar#2959]
It seems queries that involve array flattening result in a `value` wrapped result 

Query:
``` sql
SELECT 
    t0.b[*]
FROM 
    `/mongo/test/flattenable` as t0 
```

Input:
``` json
{ "a": 1, "b": [true, true, true] }
{ "a": 2, "b": [false, false] }
{ "a": 3, "b": "string" }
{ "a": 4, "b": null }
```

Output:
``` json
{ "_id": "59e9fca7a8c19bc70fdebfee", "value": true },
{ "_id": "59e9fca7a8c19bc70fdebfef", "value": true },
{ "_id": "59e9fca7a8c19bc70fdebff0", "value": true },
{ "_id": "59e9fca7a8c19bc70fdebff1", "value": false },
{ "_id": "59e9fca7a8c19bc70fdebff2", "value": false }
```

**Comment by garyb** [comment]
Ah, I think this is because I'm trying to select values at the top level, so I guess we still have the restriction that we need maps to come out, as this:

``` sql
SELECT 
    { "b": t0.b[*] }
FROM 
    `/mongo/test/flattenable` AS t0
```

Doesn't give the wrapping. That's different from mimir, as both versions work, but I assume is tricky to fix for the mongo case still?

**Comment by wemrysi** [comment]
@garyb Nice work :wink: I think this shouldn't be too bad to fix, this type of query generates a different class of mongo access than expected and one that the current unwrapping of values doesn't deal with. It should be a matter of recognizing it and eliding the wrapping.

**Comment by wemrysi** [comment]
@garyb Also, to clarify, are you running the above query via SlamData? If so can I assume there is an implicit `limit` added to it?

If I run a query analogous to yours at the repl it actually returns as expected, but if I add a limit then I get the results you're seeing.

**Comment by zeeiyerWork** [comment]
Chatted with @garyb - It's not really affecting any end-user capability, so dropping the "skull"
