### ISSUE TITLE
Quasar Extensions/API in support of import of a .zip (not produced by Slamdata)

### ISSUE THREAD

**Issue by zeeiyerWork** [precog/quasar#2964]
This is in support of https://github.com/slamdata/slamdata/issues/2319. 

The Import capability should allow the user to import an externally produced zip file. The zip file could be homogenous in terms of file-extensions or could be heterogenous. If homogenous is easier the FE needs to know, so the import dialog could inspect the zip and apprise the user of this restriction.

The ability to import data as JSON, CSV, XML or zips is key to be able to allow customers experience the full power of Mimir and Slam-data Desktop as a whole.

**Comment by nicflores** [comment]
@zeeiyerWork, this issue seems to be related to this one [#2652](https://github.com/quasar-analytics/quasar/issues/2652).
