### ISSUE TITLE
Sorting query on _id does not work properly on mongo agg.pipeline

### ISSUE THREAD

**Issue by rintcius** [precog/quasar#3007]
This query does not sort properly on mongo agg.pipeline:

```sql
select * from zips where pop < loc[1] order by `_id` limit 10
```

<details>
<summary>Query output</summary>

```
QScript Mongo (Prefer Projection):
Subset(Take)
├─ Unreferenced
├─ From
│  ╰─ Sort
│     ├─ Filter
│     │  ├─ ShiftedRead(/test/zips, ExcludeId)
│     │  ╰─ Guard
│     │     ├─ ProjectField
│     │     │  ├─ ○
│     │     │  ╰─ Constant(Str(loc))
│     │     ├─ Type(FlexArr(0, None, Top))
│     │     ├─ Guard
│     │     │  ├─ ProjectIndex
│     │     │  │  ├─ ProjectField
│     │     │  │  │  ├─ ○
│     │     │  │  │  ╰─ Constant(Str(loc))
│     │     │  │  ╰─ Constant(Int(1))
│     │     │  ├─ Type(Int, Dec, Interval, Str, Timestamp, Date, Time, or Bool)
│     │     │  ├─ Guard
│     │     │  │  ├─ ProjectField
│     │     │  │  │  ├─ ○
│     │     │  │  │  ╰─ Constant(Str(pop))
│     │     │  │  ├─ Type(Int, Dec, Interval, Str, Timestamp, Date, Time, or Bool)
│     │     │  │  ├─ Lt
│     │     │  │  │  ├─ ProjectField
│     │     │  │  │  │  ├─ ○
│     │     │  │  │  │  ╰─ Constant(Str(pop))
│     │     │  │  │  ╰─ ProjectIndex
│     │     │  │  │     ├─ ProjectField
│     │     │  │  │     │  ├─ ○
│     │     │  │  │     │  ╰─ Constant(Str(loc))
│     │     │  │  │     ╰─ Constant(Int(1))
│     │     │  │  ╰─ Undefined
│     │     │  ╰─ Undefined
│     │     ╰─ Undefined
│     ├─ Bucket
│     │  ╰─ List
│     ╰─ Order
│        ╰─ Ascending
│           ╰─ By
│              ╰─ ProjectField
│                 ├─ ○
│                 ╰─ Constant(Str(_id))
╰─ Count
   ╰─ Map
      ├─ Unreferenced
      ╰─ Constant(Int(10))

Workflow Builder:
ShapePreservingBuilder
├─ ShapePreservingBuilder
│  ├─ ShapePreservingBuilder
│  │  ├─ ShapePreservingBuilder
│  │  │  ├─ CollectionBuilder(Root())
│  │  │  │  ├─ $ReadF(test; zips)
│  │  │  │  ╰─ Schema
│  │  │  ├─ \&/(Both)
│  │  │  │  ├─ JsCore(_.loc)
│  │  │  │  ╰─ ExprOp("$loc")
│  │  │  ╰─ Chain
│  │  │     ├─ $ReadF(; )
│  │  │     ╰─ $MatchF
│  │  │        ╰─ Doc
│  │  │           ╰─ Expr($_0 -> ElemMatch(\/-(Exists(true))))
│  │  ├─ \&/(Both)
│  │  │  ├─ JsCore(_.pop < _.loc[1])
│  │  │  ╰─ ExprOp({
│  │  │            "$lt": ["$pop", { "$arrayElemAt": ["$loc", { "$literal": NumberInt("1") }] }]
│  │  │          })
│  │  ╰─ Chain
│  │     ├─ $ReadF(; )
│  │     ╰─ $MatchF
│  │        ╰─ Doc
│  │           ╰─ Expr($_0 -> Eq(Bool(true)))
│  ├─ \&/(Both)
│  │  ├─ JsCore(_._id)
│  │  ╰─ ExprOp("$_id")
│  ╰─ Chain
│     ├─ $ReadF(; )
│     ╰─ $SortF
│        ╰─ SortKey(_0 -> Ascending)
╰─ Chain
   ├─ $ReadF(; )
   ╰─ $LimitF(10)

Workflow (raw):
Chain
├─ $ReadF(test; zips)
├─ $MatchF
│  ╰─ Doc
│     ╰─ Expr($loc -> ElemMatch(\/-(Exists(true))))
├─ $ProjectF
│  ├─ Name("0" -> {
│  │       "$lt": ["$pop", { "$arrayElemAt": ["$loc", { "$literal": NumberInt("1") }] }]
│  │     })
│  ├─ Name("src" -> "$$ROOT")
│  ╰─ ExcludeId
├─ $MatchF
│  ╰─ Doc
│     ╰─ Expr($0 -> Eq(Bool(true)))
├─ $SortF
│  ╰─ SortKey(_id -> Ascending)
├─ $LimitF(10)
╰─ $ProjectF
   ├─ Name("__quasar_mongodb_sigil" -> "$src")
   ╰─ ExcludeId

Workflow (crystallized):
Chain
├─ $ReadF(test; zips)
├─ $MatchF
│  ╰─ Doc
│     ╰─ Expr($loc -> ElemMatch(\/-(Exists(true))))
├─ $ProjectF
│  ├─ Name("0" -> {
│  │       "$lt": ["$pop", { "$arrayElemAt": ["$loc", { "$literal": NumberInt("1") }] }]
│  │     })
│  ├─ Name("src" -> "$$ROOT")
│  ╰─ ExcludeId
├─ $MatchF
│  ╰─ Doc
│     ╰─ Expr($0 -> Eq(Bool(true)))
├─ $SortF
│  ╰─ SortKey(_id -> Ascending)
├─ $LimitF(10)
╰─ $ProjectF
   ├─ Name("__quasar_mongodb_sigil" -> "$src")
   ╰─ ExcludeId

MongoDB:
db.zips.aggregate(
  [
    { "$match": { "loc": { "$elemMatch": { "$exists": true } } } },
    {
      "$project": {
        "0": {
          "$lt": [
            "$pop",
            { "$arrayElemAt": ["$loc", { "$literal": NumberInt("1") }] }]
        },
        "src": "$$ROOT",
        "_id": false
      }
    },
    { "$match": { "0": true } },
    { "$sort": { "_id": NumberInt("1") } },
    { "$limit": NumberLong("10") },
    { "$project": { "__quasar_mongodb_sigil": "$src", "_id": false } }],
  { "allowDiskUse": true });
```
</details>

It looks like the `_id` here is tripping up the sorting of the query:
```
    {
      "$project": {
        "0": {
          "$lt": [
            "$pop",
            { "$arrayElemAt": ["$loc", { "$literal": NumberInt("1") }] }]
        },
        "src": "$$ROOT",
        "_id": false
      }
    },
```
Without `"_id": false` the query sorts ok. 

This issue was detected in https://github.com/quasar-analytics/quasar/pull/3001 - without this PR this query was running on Map Reduce, which doesn't have this issue. Running this query on agg.pipeline revealed it.

**Comment by zeeiyerWork** [comment]
@damonLL , @dugdun , @jdegoes -> Fyi. Since there is a workaround, not including it in 5.0.0 unless you have a different opinion.

**Comment by alissapajer** [comment]
@rintcius @zeeiyerWork what is the workaround? Is there an equivalent query we can write that doesn't hit this?

**Comment by dugdun** [comment]
If I'm reading this correctly, in AggFramework we're projecting out the `_id` field so it isn't available for sorting later on in the pipeline. The workaround is really that without the code that @rintcius mentioned, the query will fallback to using MapReduce. Is that correct? I'm not sure we have a lot of clients sorting on the MongoDB `_id` field so it might not be an issue, but that's just a guess.

**Comment by alissapajer** [comment]
Is it still a correct mongo plan if we don't include `"_id": false`? Where in the mongo planner are we making that decision?

If the plan is still correct without `"_id": false`, and we can remove that flag while still using aggregation, then the solution would be to generate that mongo plan instead. But that wouldn't be a workaround that a customer could perform; it would be a bug fix that we have to make on the backend.

**Comment by alissapajer** [comment]
#3001 includes a lot of work that we must include in 5.0.0, so we need to determine how to fix this given #3001.

**Comment by wemrysi** [comment]
@alissapajer Yes, it should be. This probably was an unintended consequence of [this change](https://github.com/quasar-analytics/quasar/pull/2892/files#diff-b8dfa9cc253bea3181a862197fd71953R163), however we can't just revert it as it wasn't correct before either (we'd include `_id` in output that didn't request it).

So it seems we either need to know when to ignore the id rather than explicitly exclude it, or stop assuming it will just be there and explicitly include it or track where the root value is and project from there (it could be obtained via the `$src` field in this example, I think) .

**Comment by alissapajer** [comment]
So, we need to know from business if this query absolutely must work in the initial 5.0.0 release or not.

**Comment by alissapajer** [comment]
Does anyone know if this query used to work in old mongo? Could someone who has easy access to old mongo give this a run?

**Comment by dugdun** [comment]
It appears to be working as expected in old Mongo (SlamData 4.2.6 with Quasar 20.14.7).

![screen shot 2017-11-01 at 12 12 43](https://user-images.githubusercontent.com/828514/32290019-4f1b14e4-befe-11e7-81d3-0e894e2fa9cf.png)

Rather I should say that the results are sorted properly on the `_id` field.

**Comment by zeeiyerWork** [comment]
@alissapajer -> I meant the workaround = what @rintcius wrote in the description:
>>> Without "_id": false the query sorts ok.

If that's reasonable, then we can fix in a later version.  That was the question asked of the folks "fyi"'ed in the initial comment. It's in 5.1.0 at this point unless its needed sooner.

**Comment by wemrysi** [comment]
@zeeiyerWork Omitting the `"_id": false` is equivalent to fixing the problem, that isn't something a user can control.

**Comment by alissapajer** [comment]
@zeeiyerWork a workaround means that there is a way that a customer can achieve their goal using a different means (e.g. by writing a different query). In this case, we don't know of a way that a customer can work around this bug. But we do know what's causing it on the backend, which is what @rintcius mentioned. So we don't have a workaround, but we have an idea of how we can fix the bug.

**Comment by alissapajer** [comment]
We may all be trying to say the same thing here, but terminology is important, which is why I clarified.

**Comment by rintcius** [comment]
Asking explicitly for `_id` in the `select` works around this issue (although it resorts to map-reduce partly):

```select `_id`, * from zips where pop < loc[1] order by `_id` limit 10```

**Comment by zeeiyerWork** [comment]
@rintcius - was independently trying to debug this. Attached is the repl output in case of query against zips in Mongo and against zips in Local (mimir) with _id being selected: Results seem consistent and as per expectation. 

[3007MimirZips.html.gz](https://github.com/quasar-analytics/quasar/files/1439688/3007MimirZips.html.gz)
[3007MongoZips.html.gz](https://github.com/quasar-analytics/quasar/files/1439689/3007MongoZips.html.gz)

**Comment by rintcius** [comment]
@zeeiyerWork 

quote from issue description:
> This issue was detected in #3001 - without this PR this query was running on Map Reduce, which doesn't have this issue. Running this query on agg.pipeline revealed it.

#3001 isn't in `master` yet, so it's still running in map-reduce
