### ISSUE TITLE
COUNT(*) sometimes fails if it is first in the SELECT clause

### ISSUE THREAD

**Issue by damonLL** [precog/quasar#3053]
The following query fails if you switch the two entries in the `SELECT` clause:
```
SELECT
  DISTINCT(Pages[*].Url.Path) AS URL,
  COUNT(*) AS Cnt
FROM `/mongodb/sc/Interactions`
WHERE
  Pages[*].Url.Path LIKE "http://%"
GROUP BY
  Pages[*].Url.Path
ORDER BY COUNT(*) DESC
LIMIT 10
```

In this instance, if `COUNT(*) AS Cnt` is first, then it fails with the error attached below:

[count.json.txt](https://github.com/quasar-analytics/quasar/files/1455348/count.json.txt)

Perhaps it because we're flattening the `Pages` array and it confuses things? Or maybe the `GROUP BY`? Not sure. But the query above, as-is, runs as expected.

**Comment by zeeiyerWork** [comment]
We do have a workaround as per @damonLL -> but need some investigation.

**Comment by zeeiyerWork** [comment]
not critical to 5.0.0 given above comment, so de-prioritizing out of November milestone.

**Comment by alissapajer** [comment]
This query is a very good example of filtering by, grouping by, and ordering by nonmappable operations, so I'm going to grab this issue to use as a test for #3021 .

**Comment by alissapajer** [comment]
I'm 💀ing this because we need to make sure at least the workaround works against qsu. Though I wouldn't be surprised if the original query works as well, unless it's a connector-specific bug.

**Comment by djspiewak** [comment]
@alissapajer I'll check it out today.

**Comment by alissapajer** [comment]
@djspiewak ordering by a nonmappable operation is implemented only locally for me, so I would expect this to error against master. 

Also, I'd like to have this as an integration test.

**Comment by alissapajer** [comment]
This is hitting `[ReifyBuckets] Expected to find a mappable region` as of my work to support nonmappable sort keys as part of #3021.

**Comment by alissapajer** [comment]
This may be tracked by #3274, but we should keep it open in case it also has a different problem.
