### ISSUE TITLE
Using ORDER BY and LIMIT returns no results

### ISSUE THREAD

**Issue by dugdun** [precog/quasar#3071]
If you remove the `ORDER BY` or `LIMIT` clause from this query you will get results. If both are there you get no results.

```
select
        A_Name as Game
    ,   B_Released as ReleaseDate
    ,   C_Recommendations as Reviews
    ,   D_Metacritic as Score
    ,   PriceInitial as Price
from
        `/hdfs/steamgames.ldjson`
order by
       A_Name asc
limit
        10
```

**Comment by alissapajer** [comment]
@dugdun do you recall what connector you tested this with?

@djspiewak I'm adding the 💀 provisionally until we figure out what's going on. This should definitely be tested against latest master.

**Comment by dugdun** [comment]
This was being run on Spark on HDFS on the test server that @rabbitonweb has been using for all his other testing.

**Comment by dugdun** [comment]
Just tested with the version that is on server which is Quasar 26.1.7 which was release a few days ago.

@rabbitonweb  do you control the updating of Quasar on this server, or was @damonLL doing that in the past?

**Comment by alissapajer** [comment]
@dugdun do you know if this issue is specific to spark or universal to all connectors?

**Comment by dugdun** [comment]
@alissapajer it looks likes it's just a problem in Spark. I just ran the above query against Q26.1.7 using MongoDB and I'm getting results back as I would expect.

**Comment by djspiewak** [comment]
As long as mongodb and mimir aren't exhibiting this issue, then we can safely unskull it.  Though it's definitely concerning that Spark would have this problem.  Needs more investigation.

**Comment by dugdun** [comment]
I do get results when testing against Mimir, but I question the validity of the results based on sorting in `DESC` order.

@djspiewak when you get a chance can we discuss?

**Comment by dugdun** [comment]
Just spoke with @djspiewak and sorting should be fixed in the latest. Will test later.

**Comment by dugdun** [comment]
Removed ☠️ label as only Spark appears to not return results for this query.

Just checked the **steamgames** file and there are three games that have a name that is a numeric value and not a string. This means that database systems that allow for different data types in the same field **could** sort differently based on their sorting rules. I would say that both Mimir and MongoDB are functioning properly based on their sorting algorithms and the difference in results **should** be expected if the sorting rules are different. Sorry for not checking out the data types for this field before commenting earlier.
