### ISSUE TITLE
Triage `distinct` unit tests

### ISSUE THREAD

**Issue by jsantos17** [precog/quasar#3075]
Branched off #2667 

There are 8 disabled tests for queries including `distinct`. Some of them just need updated expectations while others might have QScript issues or issues in the Mongo planner. Queries with QScript issues can be verified by writing tests in `PlannerQScriptSpec` to bypass QScript generation.

**Comment by jsantos17** [comment]
Just checked the state of distinct and most queries are correct and working correctly. The only two problems queries are:

| Query | Result|Plan|
|-------|------------|-----|
|`SELECT DISTINCT SUM(pop) AS totalPop, city, state FROM zips GROUP BY city`|Empty|[Link](https://gist.github.com/jsantos17/2e82cb7c18d1c7e703e8f03dea32804b)
|`SELECT DISTINCT SUM(pop) AS totalPop, city, state FROM zips GROUP BY city ORDER BY totalPop DESC`|Empty|[Link](https://gist.github.com/jsantos17/01013e63c9b68b919d8c68775f87a603)

These have autojoins in them that can probably be optimized away, but we should be getting correct results anyway.

@alissapajer, @djspiewak, @wemrysi: Any known issues in the two queries above? If not, this might be a bug in the Mongo connector.

These have `Guard`s on `ShiftedRead` so we might want to re-evaluate these two queries after #3048

**Comment by djspiewak** [comment]
These are both the same issue.  I believe @wemrysi is working on this right now.  Neither are failing because of the `Guard`s (they fail on mimir as well).

**Comment by alissapajer** [comment]
We are projecting out keys that we have not created. For example [here](https://gist.github.com/jsantos17/2e82cb7c18d1c7e703e8f03dea32804b#file-distinct-with-sum-and-group-txt-L72) we project out `"identities"` followed by `"qsu18_0"`, neither of which exist.

**Comment by alissapajer** [comment]
Also to note, [here](https://gist.github.com/jsantos17/2e82cb7c18d1c7e703e8f03dea32804b#file-distinct-with-sum-and-group-txt-L76) we project `"city"` from the right side join branch, but in the right side join branch we create a map with key `"state"`.

**Comment by wemrysi** [comment]
@alissapajer Yeah, the second bit you refer to is what I'm fixing for #3170 and the first bit should be fixed when #3204 is merged.

**Comment by jsantos17** [comment]
Awesome. I'll re-evaluate once #3204 is merged. Thanks for all the input.

**Comment by djspiewak** [comment]
@jsantos17 Can you reevaluate this?

**Comment by jsantos17** [comment]
@djspiewak just checked with latest `master` and both queries are still returning empty results.

**Comment by djspiewak** [comment]
@jsantos17 Looks like this will be fixed by @wemrysi's current work.
