### ISSUE TITLE
Reimplement path discovery on Reads

### ISSUE THREAD

**Issue by djspiewak** [precog/quasar#3095]
At present, we can only read files.  This definitely breaks connectors like marklogic, but probably also causes problems in other areas as well.  We should get back to our `DiscoverPath.ListContents`-using ways.

@wemrysi can you weigh in on whether or not this should be skulled?

**Comment by alissapajer** [comment]
There is a test in `RewriteSpec` tagged with this issue number that should be re-enabled, or otherwise dealt with, when this issue is completed.
