### ISSUE TITLE
Plan nested LeftShifts efficiently

### ISSUE THREAD

**Issue by jsantos17** [precog/quasar#3110]
The Search Card and queries including flattening of multiple fields with a common source will be planned using nested left-shifts instead of autojoins. Because of this, the Mongo connector needs to plan nested left shifts efficiently. [More information.](https://gist.github.com/djspiewak/262a5fa0e56d69746dede59320b263f6)

This should NOT depend on SQL^2, but queries like `select loc[*][*] from /mngo/db/zips` and their current QScript can be used as a starting point:

```
LeftShift
├─ LeftShift
│  ├─ ShiftedRead(/db/zips, ExcludeId)
│  ├─ Struct
│  │  ╰─ Guard
│  │     ├─ ProjectKey
│  │     │  ├─ ○
│  │     │  ╰─ Constant(Str(loc))
│  │     ├─ Type(FlexArr(0, None, FlexArr(0, None, Top)))
│  │     ├─ ProjectKey
│  │     │  ├─ ○
│  │     │  ╰─ Constant(Str(loc))
│  │     ╰─ Undefined
│  ├─ IdStatus
│  │  ╰─ IdStatus(ExcludeId)
│  ╰─ Repair
│     ╰─ Guard
│        ├─ RightSide
│        ├─ Type(FlexArr(0, None, Top))
│        ├─ RightSide
│        ╰─ Undefined
├─ Struct
│  ╰─ ○
├─ IdStatus
│  ╰─ IdStatus(ExcludeId)
╰─ Repair
   ╰─ RightSide
```

Currently this QScript plans using `mapReduce`. We need to make sure QScript like this is planned efficiently in aggregation. It's worth noting the old Mongo connector plans this query efficiently with no need for mapReduce.

Importantly, the `Struct` functions in the previous QScript will not look like this for autojoin elimination using left-shifts. It'll instead include nested projections. Details on this are still in the air.

@djspiewak: when rewriting autojoins like this, does the inner `ShiftedRead` have `ExcludeId` or `IncludeId`? We might need to prioritize #3047 for the Search Card if we still need `IncludeId`.

**Comment by djspiewak** [comment]
@jsantos17 So long as there is no actual autojoining on the results at the end (which there wouldn't be for the search card), then it *should* all be `ExcludeId`.  @wemrysi can speak to this more.

**Comment by wemrysi** [comment]
@djspiewak @jsantos17 Aye, that sounds right. We'll default to `ExcludeId` and only include if it is actually used, this is the opposite of what we do now where we pessimistically include and try to notice that we didn't use the identity after the fact.
