### ISSUE TITLE
Fix autojoin key handling for 'Both' provenance

### ISSUE THREAD

**Issue by wemrysi** [precog/quasar#3114]
Creating autojoin keys for `Both` provenance needs to properly handle the case where the left/right sides of the `Both` have the same provenance (say, from a self-join) and, for some matching candidate provenance `x` construct `(x == l) || (x == r)`.

This also means we need to resurrect constructing identity getters when creating join keys so we know how to access identities, even with unique symbols, since the same symbol may appear on either side of a join in the aforementioned self-join scenario.

**Comment by djspiewak** [comment]
One of the demo queries hits this issue, btw:

```sql
SELECT COUNT(*) AS count FROM (SELECT o.order_key AS OrderKey, o.purchase_date AS PurchaseDate, c.last_name || ", " || c.first_name AS Name, c.city AS City, c.state AS State, i.clothing_size AS Size, i.clothing_type AS Type, i.clothing_color AS Color, i.price AS UnitPrice, oi.qty AS Quantity, i.price * oi.qty AS PricePaid, SUM(i.price * oi.qty) AS TotalPaid, i.clothing_brand AS Brand FROM (SELECT * FROM (SELECT * FROM `/hdfs/customers.ldjson`) AS res WHERE res.state IN ("AK")) AS c INNER JOIN `/hdfs/orders.ldjson` AS o ON c.customer_key = o.customer_key INNER JOIN `/hdfs/ordered_items.ldjson` AS oi ON oi.order_key = o.order_key INNER JOIN `/hdfs/inventory_items.ldjson` AS i ON i.item_key = oi.item_key GROUP BY i.price * oi.qty) AS tmp__1
```

**Comment by wemrysi** [comment]
I experimented enabling the naive identity map merging on this query and it now compiles and runs, but returns a count of `0`, when it should be non-zero given my local data.

The resulting plan is quite complicated so I'm not sure if it is failing due to the identities or something else. This may mean that more queries are affected by this than I originally anticipated.
