### ISSUE TITLE
Proper abstraction for the QSU graph

### ISSUE THREAD

**Issue by wemrysi** [precog/quasar#3123]
We need an abstraction describing the QSU graph and its operations, our current approach leaks too many implementation details and makes it easy to introduce bugs.

**Comment by wemrysi** [comment]
https://github.com/snowleopard/alga-paper/releases/download/final/algebraic-graphs-haskellx.pdf (via @djspiewak).

**Comment by djspiewak** [comment]
That paper moves beyond even an abstraction.  It's just straight-up a better encoding.  Also it's awesome.

Here's the ICFP paper: https://github.com/snowleopard/alga-paper/releases/download/final/algebraic-graphs.pdf
