### ISSUE TITLE
Several tests now failing in couchbase under qsu

### ISSUE THREAD

**Issue by djspiewak** [precog/quasar#3158]
This is a megabug aggregation.  TODO break this out

- `./resultFile/basicAnalyticQuery.test`
- `./couchbase/rightKeyJoin.test`
- `./filterSkipLimitCount.test`
- `./couchbase/leftKeyJoinMultipleSelect.test`
- `./couchbase/leftKeyJoin.test`

**Comment by zeeiyerWork** [comment]
@nicflores -> fyi... (not needed for 5.0 perhaps, but we'd soon need to get these fixed).
