### ISSUE TITLE
Handle generated `_id`s when reading results from a collection Quasar wrote back

### ISSUE THREAD

**Issue by jsantos17** [precog/quasar#3176]
The [basic analytic query test](https://github.com/quasar-analytics/quasar/blob/8c30259dffa4eaf56acca3d78783374907129793/it/src/main/resources/tests/resultFile/basicAnalyticQuery.test) is failing because of an extraneous `_id` in the result. This is unrelated to #3152.

The query is planned correctly and the test passes when run in streaming mode. The planner generates the correct plan and the correct results are returned (without `_id`). However, when Quasar writes back the results into a temporary collection, MongoDB generates `_id`s for each document. This, of course, makes the result no longer match the expectation.

This was working before QSU was merged into `master`. Investigating how this was working before might prove fruitful. Old Mongo worked around this problem by special handling of the `_id` field. The Old Mongo approach is fragile and sometimes deletes real `_id`s (when implemented in New Mongo).

cc @wemrysi

**Comment by zeeiyerWork** [comment]
One approach could be to write a "special-field" when quasar writes - so that we can ignore the _id when read back (so we know for sure which is customer data versus synthetic temporary data?) ? @jsantos17 or @wemrysi - any thoughts on this approach?

**Comment by zeeiyerWork** [comment]
@jsantos17 opines that this does not impact end-user queries (just tests that explicitly write back) - hence the deprioritization.

**Comment by jsantos17** [comment]
Yes, this shouldn't affect any queries unless the user explicitly asks for the result of a query to be written into a collection. Intermediate result write back is unaffected.

So the question is, does the frontend ever make queries intended to be stored in a Mongo collection? @garyb, @beckyconning?
