### ISSUE TITLE
Add ITs for tests in PlannerSpec

### ISSUE THREAD

**Issue by rintcius** [precog/quasar#3178]
Passing tests in `PlannerSpec` now only verify the sequence of pipeline ops instead of the exact workflow. We need to add ITs for these tests to ensure they return correct results.

**Comment by zeeiyerWork** [comment]
@rintcius -> seems like some ITs (if not an exhaustive) of this nature are needed before 5.0.0 ships? 
So would you agree that this needs to be skulled?

**Comment by rintcius** [comment]
@zeeiyerWork it's good to add them soon, but not strictly necessary for 5.0.0

**Comment by zeeiyerWork** [comment]
ok unscheduled it for 5.0
