### ISSUE TITLE
Web API doesn't work even though REPL works (path issue)

### ISSUE THREAD

**Issue by sreejithr** [precog/quasar#3207]
I setup a Quasar instance connected to a Mongo sharded replica set with nginx infront. **The REPL works fine. But the REST interface doesn't**. 

To get a sense of the "file" structure,
```
(v27.0.10) 💪 $ ls
dbs@ (mongodb)
(v27.0.10) 💪 $ cd dbs@
(v27.0.10) 💪 $ ls
heroku_vzf3h06d/
```
And inside this, there's all my collections. I wanted to do a `select *` on the `users` collection (say).

I tried all of the below urls: **(None worked)**
1. `/query/fs/dbs/heroku_vzf3h06d/?q=select * from users`
2. `/query/fs/dbs@/heroku_vzf3h06d/?q=select * from users`
3. `/query/fs/dbs@ (mongodb)/heroku_vzf3h06d/?q=select * from users`
4. `/query/fs/dbs/?q=select * from users`
5. `/query/fs/heroku_vzf3h06d/?q=select * from users`

Then I added `/local` infront and tried a couple **(None worked)**
1. `/query/fs/local/heroku_vzf3h06d/?q=select * from users`
2. `/query/fs/local/?q=select * from users`

For all this, I got this error in the API:
```
{
  "error": {
    "status": "Directory path expected.",
    "detail": {
      "message": "Expected '/dbs/heroku_vzf3h06d' to be a directory.",
      "path": "/dbs/heroku_vzf3h06d"
    }
  }
}
```
Here's my config file:
```
{
  "server": {
    "port": 8080
  },
  "metastore": {
    "database": {
      "h2": {
        "location": "~/quasar-metastore.db"
      }
    }
  },
  "mountings": {
    "/dbs/": {
      "mongodb": {
        "connectionUri": "<url to mongo replica set>"
      }
    }
  }
}
```
Quasar version: `27.0.10`

**Comment by drostron** [comment]
The error "Expected '/dbs/heroku_vzf3h06d' to be a directory." leads me to believe nginx might be stripping a trailing slash. @sreejithr could you check your nginx conf to see if that might be the case?
