### ISSUE TITLE
Plan date comparisons using ranges

### ISSUE THREAD

**Issue by jsantos17** [precog/quasar#3232]
MongoDB datetime comparison operators operate on instants. This can lead to unexpected results as two dates will only match when days, year, hour and seconds match exactly. For instance, the query `select * from zips where ts = date("2017-01-01")` plans (incorrectly) as `db.zips.find({ "ts": ISODate("2017-01-01T00:00:00Z") })`. Instead, the query should be planned with a range:

```
db.zips.find(
  {
    "$or": [
      { "ts": { "$lt": ISODate("2017-01-01T00:00:00Z") } },
      { "ts": { "$gte": ISODate("2017-01-02T00:00:00Z") } }]
  });
```

Similarly, `select * from zips where ts != date("2017-01-01")` should exclude the range representing the date and should be planned as:

```
db.zips.find(
  {
    "$or": [
      { "ts": { "$lt": ISODate("2017-01-01T00:00:00Z") } },
      { "ts": { "$gte": ISODate("2017-01-02T00:00:00Z") } }]
  });
```

and not with `$neq`. The `plan filter on date` test in `quasar.physical.mongodb.PlannerSql2ExactSpec` tests this behavior.

**Comment by zeeiyerWork** [comment]
Worthwhile asking @edmundnoble if his PR going to fix this.
If so, we target 5.1.0 for this.

**Comment by edmundnoble** [comment]
My PR doesn't implement the datetime functionality for any connectors other than Spark and Mimir, so no, it won't be fixing this.

**Comment by zeeiyerWork** [comment]
Seems like a low LOE localized to the mongo-connector
