### ISSUE TITLE
String comparison is broken

### ISSUE THREAD

**Issue by cryogenian** [precog/quasar#3242]
```sql
select * from `/mimir/flatViz`
where false 
or measureOne > 0
```

Returns 253 records

```sql
select * from `/mimir/flatViz`
where false 
or measureOne > 0
or lower(measureOne) > lower("0")
```

Returns 0 records

```sql
select * from `/mimir/flatViz`
where false 
or measureTwo > 0
```

Returns 253 records

```sql 
select * from `/mimir/flatViz`
where false 
or measureTwo > 0
or measureOne > "0"
```

Returns 0 records

```sql
select * from `/mimir/flatViz`
where false 
or measureTwo > 0
or measureOne <> "0"
```

Returns all records 

```sql
select * from `/mimir/flatViz`
where false 
or measureTwo > 0
or measureOne = "0"
```

Returns 253 records

Quasar 27.1.16. 

Looks like string comparison is broken.

**Comment by cryogenian** [comment]
Ah, yep two interesting cases 
```sql
select * from `/mimir/flatViz`
where true 
or measureTwo > 0 
or measureOne = "0"
```

Returns all 

```sql 
select * from `/mimir/flatViz`
where measureOne <> "0"
or measureOne = "0"
or measureOne > "0"
```

I tried to mix up `measureOne`, `measureTwo` (these are numerical) and `seriesOne` (these is string only projection). 

Even the simplest one `select * from `/mimir/flatViz` where seriesOne > "0"` doesn't work and breaks ors chain.

**Comment by zeeiyerWork** [comment]
Important as described by @cryogenian since it impacts search/

**Comment by djspiewak** [comment]
This isn't broken, this is by mimir's definition of what strings mean.  From mimir's perspective, you're using a numeric operation on strings.  This is something we need to fix, but it's not going to happen for 5.0.

@cryogenian Can you elaborate here on why this affects search capability?  We could probably special-case this particular part of the mimir data model reconciliation task (a very large post-5.0 goal) for this one ticket if it's absolutely necessary, but I would rather just unskull it and pick this up when we do the rest of the reconciliation.

**Comment by cryogenian** [comment]
@djspiewak Suppose we have a search query `foo:>1` it compiles to `foo > 1 or lower(foo) > "1" or foo > 1.0`

Basically it's okay to be incomparable for strings I suppose, but `or` binop is broken. Like `meaninglessStuff or true` evals to `false`

**Comment by djspiewak** [comment]
Right, I feel like the `or`/`and` issue is probably bigger (also much easier to fix), because it affects any exploration of heterogeneous data.

**Comment by djspiewak** [comment]
Unskulling per @jdegoes.  PR is out for the `or`/`and` issue.  The ability to use `>` and `<` on non-numeric values in mimir is something that we'll be addressing in 5.1 and beyond.

**Comment by zeeiyerWork** [comment]
OK thanks for the clarification. Fyi @cryogenian...
