### ISSUE TITLE
Identical temp work areas appear throughout Quasar file system and cannot be deleted

### ISSUE THREAD

**Issue by damonLL** [precog/quasar#3248]
Quasar v 27.2.3

While waiting for a particularly long-running query to complete, I killed MongoDB. Not sure if this caused the following situation:

Three temporary "out" collections / folders appear at three separate locations:

- At the top level (same level of mounts) such as `/out123...`, etc.
- At the path `/wg/out123...`, `/wg/out234...`, etc.
- At the path `/wg/emclab/out123...`, etc.

These 3 tmp out collections appear at 3 separate areas. Interestingly, the `/mongodb` and `/wg` mounts point to the same MongoDB, but the collections do not appear in the `/mongodb` mount

This leads me to believe these are entries in the metastore vs inside of MongoDB.

I'm also unable to delete these through the SlamData UI. I've also opened the H2 database console but wasn't able to locate the relevant information.

A few screenshots follow to show the situation:

<img width="377" alt="m1" src="https://user-images.githubusercontent.com/7375598/33697645-8da1955e-dacd-11e7-9a7a-00b20baeb7b2.png">

<img width="381" alt="m2" src="https://user-images.githubusercontent.com/7375598/33697612-6c074df8-dacd-11e7-81ed-94375372968c.png">

**Comment by alissapajer** [comment]
@jdegoes can you weigh in on if this should be skulled or not?

**Comment by jdegoes** [comment]
Not skulled. /cc @beckyconning
