### ISSUE TITLE
PostgreSQL connector

### ISSUE THREAD

**Issue by EncodePanda** [precog/quasar#3265]
- [x] ReadFile
- [x] WriteFile
- [x] ManageFile
- [x] QueryFile
- [ ] Planner
- [ ] integration tests
- [ ] demoable environment

**Comment by kciesielski** [comment]
How about splitting the Planner point? Like:
[] Shifted Read
[] Core Planner (Map)
[] MapFuncCore  (Basic)
[] Sort 
[] Filter
[] Join
[] Reduce
[] MapFuncCore (remaining)
I'm not sure what else :)
