### ISSUE TITLE
Bad assumptions about wrapped buckets

### ISSUE THREAD

**Issue by djspiewak** [precog/quasar#3272]
`subqueryGroupBy.test` and possibly also `unsupportedTests.test`.  This appears to be an issue on both mimir and mongo, but maybe different causes.

**Comment by alissapajer** [comment]
We could also just add `Distinct` to qscript, either as an optional coproduct node, or as a required one (meaning we have to update each connector, but that might not be that hard).

**Comment by djspiewak** [comment]
I'm legit terrified about the scala compilation time implications of that though.

**Comment by alissapajer** [comment]
That's all too fair :(

Moving forward we can't have compile times preventing us from doing the right thing, but that's not something we're about to tackle pre-5.0. It might be worth adding the node unimplemented everywhere, and benchmarking the compile times, if someone has a computer with some CPU cycles to spare...

**Comment by djspiewak** [comment]
Yeah that might be worth doing.  It's a particularly interesting case in the above, since neither of the queries in question involve `distinct`!  It's just that the pattern is the same as what gets generated from a `Distinct` node.

**Comment by alissapajer** [comment]
Oh, that's actually really interesting. I wonder if there is a more general pattern we want to detect in qsu.

**Comment by djspiewak** [comment]
I was thinking about it. I'm not yet convinced that interpreting it as `distinct` is universally the right thing to do though.  And in this particular case, it only exists because we don't have join reassociation.  But maybe…

I'd venture a guess that most backends are going to have a primitive `distinct` that is more efficient than reduction.

**Comment by djspiewak** [comment]
I figured this out.  At least for mimir, it has nothing to do with `distinct` recognition.  Rather, it's the fact that we *always* used to get reduce buckets wrapped in an array.  Now, since we get them separated, we're hitting some code paths that were never checked before, and are in fact buggy.  I would venture to guess that mongo is having the same problem.  (@jsantos17 / @rintcius ?)

**Comment by rintcius** [comment]
https://gist.github.com/rintcius/160625ed8181269ba39fd87449eee476 shows the same problem as `subqueryGroupBy.test` but is smaller. The problem is that the last operation in the pipeline is map-reduce. When this is the case the sorting is not done. We have a rewrite in place - `mapBeforeSort` - that avoids this in some cases, but not all. 

`unsupportedTests.test` has another issue, it doesn't return any results. Haven't looked at it in detail, but here's the plan: https://gist.github.com/rintcius/8e33fab7ac11ea9bcf42aa22b295d619

**Comment by jsantos17** [comment]
@rintcius would performing `mapBeforeSort` at the workflow level instead of the QScript level help with `subqueryGroupBy.test`? Do we have an issue for that?

**Comment by rintcius** [comment]
@jsantos17 Yes, there's this issue #3063 - needs further investigation with respect to how to fix this, I am not seeing a simple solution here.

**Comment by rintcius** [comment]
On old mongo none of these queries worked either, so no regression compared to old mongo:

```
$ SELECT ceil(100 * SUM(pop) / (SELECT SUM(pop) FROM zips)), state FROM zips GROUP BY state ORDER BY state LIMIT 5
Quasar error: failed to merge

$ SELECT SUM(pop), (SELECT SUM(pop) FROM zips), state FROM zips GROUP BY state ORDER BY state LIMIT 5
Quasar error: failed to merge

$ select name from newTests where count(backends{_}) = 12 order by name limit 5
Quasar error: The function 'ShiftMap' is recognized but not supported by this back-end. (in workflow planner)
```
