### ISSUE TITLE
Scaladoc Unavailable from Link

### ISSUE THREAD

**Issue by ChristopherDavenport** [precog/quasar#3275]
I attempted to follow the link to the scaladoc from http://quasar-analytics.org/docs/scaladoc/ which directed me to http://104.236.166.167:8180/job/Quasar/lastSuccessfulBuild/artifact/core/target/scala-2.11/api/index.html#package which was either unavailable or blocked in some manner.

I confirmed with isitup that it wasn't just me.

**Comment by djspiewak** [comment]
Yeah we should change the link so that it points to javadoc.io or something similar, since quasar's javadoc is all on maven central.
