### ISSUE TITLE
Improve unsupported filesystem type error message

### ISSUE THREAD

**Issue by beckyconning** [precog/quasar#3312]
`There was a problem saving the mount: An unknown error ocurred: 400 "{ \"error\": { \"status\": \"Invalid mount configuration.\", \"detail\": { \"reasons\": [ \"Unsupported filesystem type: mongodb\" ] } } }`

<img width="613" alt="screen shot 2017-12-15 at 13 19 57" src="https://user-images.githubusercontent.com/457901/34043855-aeeeeaf8-e19a-11e7-9c76-234159523b8d.png">

Should explain that a plugin is needed and fit one the formats outlined here:

https://github.com/slamdata/purescript-quasar/blob/master/src/Quasar/QuasarF/Interpreter/Internal.purs#L185

**Comment by garyb** [comment]
I'm not sure about this:

> Should explain that a plugin is needed

As I think Quasar only reports errors, it doesn't provide suggestions on how to fix things. So unless we're going to move towards that generally, it's perhaps more the responsibility of the frontend to display the suggestion. To do that we'd ideally need the error tagging/identification thing that has been talked about a few times. Here might be a good place to start doing that!

Just my 2p though.

**Comment by garyb** [comment]
#2791 would help with this specific case too, since we wouldn't be showing the option to mount `mongodb` even, if that was available.
