### ISSUE TITLE
Plan LeftShifts with IncludeId using `$unwind`'s includeArrayIndex

### ISSUE THREAD

**Issue by jsantos17** [precog/quasar#3319]
Relevant documentation: https://docs.mongodb.com/manual/reference/operator/aggregation/unwind/#pipe._S_unwind

When planning `LeftShift`s, the `Id` flag is simply passed through inside the newly created `FlatenningBuilder`. The choice of whether to plan the `FlatteningBuilder` with `$unwind` (agg) or `$simpleMap` (mapReduce) is made in the `toWorkflow` function.

**Comment by zeeiyerWork** [comment]
In talking with @jsantos17 - several queries do need it (of the type -> `select a[*] + b[*] from foo`) and @rintcius is taking a look - hence the December/5.0.0 labels. Thanks.
